# North Carolina Primary Election Results - March 3, 2026 - Data cleaning, analysis, & mapping

We are going to create maps from the election results from the North Carolina Primary Election that occurred on March 3, 2026. 

**NC Board of Elections** handles tallying and certifying all election results and provides downloadable results for each election. 

**NC Board of Elections** also provides geographic shape files for all voting precincts in all 100 counties of North Carolina. Note: These precincts were recently redrawn and certified in December of 2025. Make sure you have the latest shape files that have the most up-to-date precincts.

## Analysis
This analysis and mapping project will strictly use the three counties that make up the **"Triangle"** i.e. **Wake, Durham, and Orange counties**.

### Cleaning data
Before we merge the election results with geospatial shape files, we need to confirm that the precinct id's on both data sets match. We will be merging data on precinct id and county name. If there are any mismatches, investigate why, and clean it up.

For example, in the Triangle counties analysis, Durham county has precinct ids as 01, 02, 03, ..., 09. On the geospatial shape files, these precinct ids showed as above, 01, 02, 03, ..., 09. However, in the election results data, these same precinct ids showed as 1, 2, 3, ..., 9, which cause a mismatch when attempting to merge the two data sets.

Next step is to merge the two data sets together.

Data pipeline steps
- Read election results csv
- filter for contest
- summarize contest (winner, runner-up, margin, etc)
- join with precinct geodata
- save as geojson
- import with mapbox gl js

In [1]:
import sys

print(sys.executable)

/Users/binguyen/.venvs/lede/bin/python

In [387]:
import os
import geopandas as gpd
import pandas as pd
import pydash

In [1025]:
script_dir = os.path.dirname(os.path.abspath('analysis.ipynb'))

In [389]:
csv_file_path = os.path.join(script_dir, '..', 'input', 'nc_primary_election_results_pct_20260303_RAW.csv')

In [390]:
results = pd.read_csv(csv_file_path)

## Filter election results by contest of choice

In [391]:
sorted(results["Contest Name"].unique())

['ALAMANCE COUNTY BOARD OF COMMISSIONERS (DEM)',
 'ALAMANCE COUNTY BOARD OF COMMISSIONERS (REP)',
 'ALAMANCE COUNTY CLERK OF SUPERIOR COURT (REP)',
 'ALAMANCE COUNTY SHERIFF (REP)',
 'ALEXANDER COUNTY BOARD OF COMMISSIONERS (REP)',
 'ALEXANDER COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'ALEXANDER COUNTY CLERK OF SUPERIOR COURT (REP)',
 'ALEXANDER COUNTY REGISTER OF DEEDS (REP)',
 'ALLEGHANY COUNTY BOARD OF COMMISSIONERS (REP)',
 'ANSON COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'ANSON COUNTY BOARD OF EDUCATION AT-LARGE (DEM)',
 'ANSON COUNTY SHERIFF (DEM)',
 'ASHE COUNTY BOARD OF COMMISSIONERS (REP)',
 'ASHE COUNTY BOARD OF EDUCATION (REP)',
 'ASHE COUNTY SHERIFF (REP)',
 'AVERY COUNTY BOARD OF COMMISSIONERS (REP)',
 'AVERY COUNTY BOARD OF EDUCATION',
 'AVERY COUNTY CLERK OF SUPERIOR COURT (REP)',
 'BEAUFORT COUNTY BOARD OF COMMISSIONERS (REP)',
 'BEAUFORT COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'BEAUFORT COUNTY BOARD OF EDUCATION DISTRICT 04 (REP)',
 'BEAUFORT COUNTY BOARD OF EDUCATION DISTRICT 06 (REP)',
 'BEAUFORT COUNTY BOARD OF EDUCATION DISTRICT 08 (REP)',
 'BEAUFORT COUNTY SHERIFF (REP)',
 'BERTIE COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (DEM)',
 'BERTIE COUNTY SHERIFF (DEM)',
 'BLADEN COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'BLADEN COUNTY BOARD OF EDUCATION DISTRICT 01 (DEM)',
 'BLADEN COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'BLADEN COUNTY SHERIFF (DEM)',
 'BLADEN COUNTY SHERIFF (REP)',
 'BRUNSWICK COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'BRUNSWICK COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'BRUNSWICK COUNTY SHERIFF (REP)',
 'BUNCOMBE COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'BUNCOMBE COUNTY SHERIFF (REP)',
 'BURKE COUNTY BOARD OF COMMISSIONERS (REP)',
 'CABARRUS COUNTY BOARD OF COMMISSIONERS (REP)',
 'CABARRUS COUNTY CLERK OF SUPERIOR COURT (REP)',
 'CABARRUS COUNTY SCHOOLS BOARD OF EDUCATION (REP)',
 'CALDWELL COUNTY BOARD OF COMMISSIONERS (REP)',
 'CALDWELL COUNTY BOARD OF EDUCATION (REP)',
 'CARTERET COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'CARTERET COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'CARTERET COUNTY BOARD OF COMMISSIONERS DISTRICT 06 (REP)',
 'CARTERET COUNTY BOARD OF EDUCATION DISTRICT 01 (REP)',
 'CARTERET COUNTY SHERIFF (REP)',
 'CASWELL COUNTY BOARD OF COMMISSIONERS AT-LARGE (UNEXPIRED) (DEM)',
 'CASWELL COUNTY BOARD OF COMMISSIONERS AT-LARGE (UNEXPIRED) (REP)',
 'CASWELL COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'CASWELL COUNTY BOARD OF EDUCATION DISTRICT 01',
 'CASWELL COUNTY BOARD OF EDUCATION DISTRICT 02',
 'CASWELL COUNTY BOARD OF EDUCATION DISTRICT 05',
 'CASWELL COUNTY CLERK OF SUPERIOR COURT (REP)',
 'CATAWBA COUNTY BOARD OF COMMISSIONERS (REP)',
 'CATAWBA COUNTY CLERK OF SUPERIOR COURT (REP)',
 'CATAWBA COUNTY SCHOOLS BOARD OF EDUCATION (REP)',
 'CATAWBA COUNTY SHERIFF (REP)',
 'CHATHAM COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (DEM)',
 'CHATHAM COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (DEM)',
 'CHEROKEE COUNTY BOARD OF COMMISSIONERS DISTRICT I (REP)',
 'CHEROKEE COUNTY BOARD OF COMMISSIONERS DISTRICT III (REP)',
 'CHEROKEE COUNTY BOARD OF COMMISSIONERS DISTRICT IV (REP)',
 'CHEROKEE COUNTY BOARD OF EDUCATION AT-LARGE (REP)',
 'CHEROKEE COUNTY BOARD OF EDUCATION DISTRICT II (REP)',
 'CHEROKEE COUNTY BOARD OF EDUCATION DISTRICT III (REP)',
 'CHEROKEE COUNTY SHERIFF (REP)',
 'CITY OF ASHEVILLE CITY COUNCIL',
 'CITY OF HENDERSONVILLE TRANSPORTATION BONDS REFERENDUM',
 'CITY OF LINCOLNTON MAYOR (REP)',
 'CITY OF MONROE COUNCIL (REP)',
 'CITY OF MONROE MAYOR (REP)',
 'CITY OF MOUNT AIRY COMMISSIONER NORTH WARD',
 'CITY OF RALEIGH CITY COUNCIL AT-LARGE',
 'CITY OF RALEIGH CITY COUNCIL DISTRICT C',
 'CLAY COUNTY BOARD OF COMMISSIONERS (REP)',
 'CLAY COUNTY BOARD OF EDUCATION (REP)',
 'CLAY COUNTY SHERIFF (REP)',
 'CLEVELAND COUNTY BOARD OF COMMISSIONERS (REP)',
 'CLEVELAND COUNTY BOARD OF EDUCATION (REP)',
 'CLINTON CITY SCHOOLS BOARD OF EDUCATION',
 'COLUMBUS COUNTY BOARD OF COMMISSIONERS DISTRICT 06 (REP)',
 'COLUMBUS COUNTY BOARD OF COMMISSIONERS DISTRICT 07 (DEM)',
 'COLUMBUS COUNTY SHERIFF (REP)',
 'CRAVEN COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'CRAVEN COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (REP)',
 'CRAVEN COUNTY BOARD OF COMMISSIONERS DISTRICT 07 (REP)',
 'CRAVEN COUNTY BOARD OF EDUCATION DISTRICT 06 (REP)',
 'CRAVEN COUNTY SHERIFF (REP)',
 'CUMBERLAND COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'CUMBERLAND COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'CUMBERLAND COUNTY SHERIFF (DEM)',
 'CURRITUCK COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'CURRITUCK COUNTY BOARD OF COMMISSIONERS AT-LARGE (REP)',
 'CURRITUCK COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'CURRITUCK COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (REP)',
 'DARE COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'DARE COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'DARE COUNTY BOARD OF EDUCATION DISTRICT 01 (REP)',
 'DARE COUNTY SHERIFF (REP)',
 'DAVIDSON COUNTY BOARD OF COMMISSIONERS (REP)',
 'DAVIDSON COUNTY CLERK OF SUPERIOR COURT (REP)',
 'DAVIDSON COUNTY SHERIFF (REP)',
 'DAVIE COUNTY BOARD OF COMMISSIONERS (REP)',
 'DAVIE COUNTY BOARD OF EDUCATION (REP)',
 'DISTRICT ATTORNEY DISTRICT 09 (REP)',
 'DISTRICT ATTORNEY DISTRICT 10 (DEM)',
 'DISTRICT ATTORNEY DISTRICT 15 (REP)',
 'DISTRICT ATTORNEY DISTRICT 16 (DEM)',
 'DISTRICT ATTORNEY DISTRICT 19 (REP)',
 'DISTRICT ATTORNEY DISTRICT 21 (DEM)',
 'DISTRICT ATTORNEY DISTRICT 36 (REP)',
 'DISTRICT ATTORNEY DISTRICT 40 (DEM)',
 'DISTRICT ATTORNEY DISTRICT 41 (REP)',
 'DUPLIN COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'DUPLIN COUNTY CLERK OF SUPERIOR COURT (REP)',
 'DUPLIN COUNTY SHERIFF (REP)',
 'DURHAM COUNTY BOARD OF EDUCATION DISTRICT 01',
 'DURHAM COUNTY BOARD OF EDUCATION DISTRICT 02',
 'DURHAM COUNTY BOARD OF EDUCATION DISTRICT 03',
 'DURHAM COUNTY BOARD OF EDUCATION DISTRICT 04',
 'DURHAM COUNTY CLERK OF SUPERIOR COURT (DEM)',
 'DURHAM COUNTY SHERIFF (DEM)',
 'EDGECOMBE COUNTY BOARD OF COMMISSIONERS DISTRICT 06 (DEM)',
 'EDGECOMBE COUNTY BOARD OF EDUCATION DISTRICT 01',
 'EDGECOMBE COUNTY BOARD OF EDUCATION DISTRICT 03',
 'EDGECOMBE COUNTY BOARD OF EDUCATION DISTRICT 05',
 'EDGECOMBE COUNTY BOARD OF EDUCATION DISTRICT 07',
 'FORSYTH COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'FORSYTH COUNTY BOARD OF COMMISSIONERS AT-LARGE (REP)',
 'FORSYTH COUNTY BOARD OF COMMISSIONERS DISTRICT A (DEM)',
 'FORSYTH COUNTY BOARD OF COMMISSIONERS DISTRICT B (DEM)',
 'FORSYTH COUNTY BOARD OF EDUCATION AT-LARGE (DEM)',
 'FORSYTH COUNTY BOARD OF EDUCATION DISTRICT 01 (DEM)',
 'FORSYTH COUNTY BOARD OF EDUCATION DISTRICT 02 (DEM)',
 'FORSYTH COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'FRANKLIN COUNTY BOARD OF COMMISSIONERS AT-LARGE SEAT 06 (REP)',
 'FRANKLIN COUNTY BOARD OF EDUCATION AT-LARGE SEAT 07',
 'FRANKLIN COUNTY BOARD OF EDUCATION DISTRICT 01',
 'FRANKLIN COUNTY BOARD OF EDUCATION DISTRICT 05',
 'GASTON COUNTY BOARD OF COMMISSIONERS DALLAS TWP (REP)',
 'GASTON COUNTY BOARD OF EDUCATION GASTONIA TWP (DEM)',
 'GASTON COUNTY SHERIFF (REP)',
 'GATES COUNTY BOARD OF EDUCATION DISTRICT 01',
 'GATES COUNTY BOARD OF EDUCATION DISTRICT 02 (UNEXPIRED)',
 'GATES COUNTY BOARD OF EDUCATION DISTRICT 03',
 'GATES COUNTY BOARD OF EDUCATION DISTRICT 05',
 'GATES COUNTY LOCAL SALES AND USE TAX REFERENDUM',
 'GRAHAM COUNTY BOARD OF COMMISSIONERS (REP)',
 'GRAHAM COUNTY SHERIFF (REP)',
 'GRANVILLE COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'GRANVILLE COUNTY BOARD OF EDUCATION DISTRICT 01',
 'GRANVILLE COUNTY BOARD OF EDUCATION DISTRICT 02',
 'GRANVILLE COUNTY BOARD OF EDUCATION DISTRICT 06',
 'GRANVILLE COUNTY LOCAL SALES AND USE TAX REFERENDUM',
 'GRANVILLE COUNTY SHERIFF (REP)',
 'GREENE COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (DEM)',
 'GUILFORD COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'GUILFORD COUNTY BOARD OF COMMISSIONERS DISTRICT 07 (DEM)',
 'GUILFORD COUNTY BOARD OF EDUCATION DISTRICT 04 (DEM)',
 'GUILFORD COUNTY BOARD OF EDUCATION DISTRICT 06 (DEM)',
 'GUILFORD COUNTY CLERK OF SUPERIOR COURT (DEM)',
 'GUILFORD COUNTY SHERIFF (REP)',
 'HALIFAX COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'HALIFAX COUNTY CLERK OF SUPERIOR COURT (DEM)',
 'HALIFAX COUNTY SCHOOLS BOARD OF EDUCATION',
 'HARNETT COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'HAYWOOD COUNTY BOARD OF COMMISSIONERS (REP)',
 'HAYWOOD COUNTY REGISTER OF DEEDS (REP)',
 'HAYWOOD COUNTY SHERIFF (REP)',
 'HAYWOOD COUNTY TAX COLLECTOR (REP)',
 'HENDERSON COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'HENDERSON COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (REP)',
 'HOKE COUNTY BOARD OF COMMISSIONERS (DEM)',
 'HYDE COUNTY LOCAL SALES AND USE TAX REFERENDUM',
 'IREDELL COUNTY BOARD OF COMMISSIONERS (REP)',
 'IREDELL COUNTY CLERK OF SUPERIOR COURT (REP)',
 'IREDELL-STATESVILLE SCHOOLS BOARD OF EDUCATION DISTRICT 01 (REP)',
 'IREDELL-STATESVILLE SCHOOLS BOARD OF EDUCATION DISTRICT 03 (REP)',
 'IREDELL-STATESVILLE SCHOOLS BOARD OF EDUCATION DISTRICT 05 (REP)',
 'JACKSON COUNTY BOARD OF COMMISSIONERS CHAIRMAN (DEM)',
 'JACKSON COUNTY BOARD OF COMMISSIONERS CHAIRMAN (REP)',
 'JACKSON COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'JACKSON COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'JACKSON COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'JACKSON COUNTY SHERIFF (REP)',
 'JOHNSTON COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'JOHNSTON COUNTY BOARD OF COMMISSIONERS DISTRICT 07 (REP)',
 'JOHNSTON COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'JOHNSTON COUNTY SHERIFF (REP)',
 'JONES COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'JONES COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'JONES COUNTY BOARD OF EDUCATION (REP)',
 'JONES COUNTY SHERIFF (REP)',
 'KANNAPOLIS CITY SCHOOLS BOARD OF EDUCATION AREA I',
 'LENOIR COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'LENOIR COUNTY BOARD OF EDUCATION DISTRICT 01 (REP)',
 'LINCOLN COUNTY BOARD OF COMMISSIONERS (REP)',
 'LINCOLN COUNTY BOARD OF EDUCATION AT-LARGE (REP)',
 'LINCOLN COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'LINCOLN COUNTY CLERK OF SUPERIOR COURT (REP)',
 'LINCOLN COUNTY REGISTER OF DEEDS (REP)',
 'MACON COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'MACON COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'MACON COUNTY SHERIFF (REP)',
 'MADISON COUNTY BOARD OF COMMISSIONERS (REP)',
 'MCDOWELL COUNTY BOARD OF COMMISSIONERS (REP)',
 'MCDOWELL COUNTY BOARD OF EDUCATION MARION DISTRICT (REP)',
 'MCDOWELL COUNTY SHERIFF (REP)',
 'MECKLENBURG COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'MECKLENBURG COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'MECKLENBURG COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'MECKLENBURG COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (DEM)',
 'MECKLENBURG COUNTY SHERIFF (DEM)',
 'MITCHELL COUNTY BOARD OF COMMISSIONERS (REP)',
 'MITCHELL COUNTY CLERK OF SUPERIOR COURT (REP)',
 'MITCHELL COUNTY SHERIFF (REP)',
 'MONTGOMERY COUNTY BOARD OF COMMISSIONERS AT-LARGE (REP)',
 'MOORE COUNTY BOARD OF COMMISSIONERS DISTRICT III (REP)',
 'MOORE COUNTY BOARD OF EDUCATION MEMBER AT-LARGE',
 'MOORE COUNTY CLERK OF SUPERIOR COURT (REP)',
 'MOREHEAD CITY MAYOR',
 'NASH COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'NASH COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (REP)',
 'NASH COUNTY BOARD OF COMMISSIONERS DISTRICT 07 (REP)',
 'NASH COUNTY CLERK OF SUPERIOR COURT (REP)',
 'NC COURT OF APPEALS JUDGE SEAT 01 (REP)',
 'NC COURT OF APPEALS JUDGE SEAT 03 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 02 SEAT 02 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 10A SEAT 01 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 14 SEAT 03 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 14 SEAT 05 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 16 SEAT 02 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 16 SEAT 05 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 26 SEAT 18 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 29 SEAT 01 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 29 SEAT 02 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 31 SEAT 04 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 32 SEAT 06 (UNEXPIRED) (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 33 SEAT 04 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 34 SEAT 02 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 35 SEAT 01 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 36 SEAT 05 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 37 SEAT 04 (REP)',
 'NC DISTRICT COURT JUDGE DISTRICT 40 SEAT 03 (DEM)',
 'NC DISTRICT COURT JUDGE DISTRICT 41 SEAT 01 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 001 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 004 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 006 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 006 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 009 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 016 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 017 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 022 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 023 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 025 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 026 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 027 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 028 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 032 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 032 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 035 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 037 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 038 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 043 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 043 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 045 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 048 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 050 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 051 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 055 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 059 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 060 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 065 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 067 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 073 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 078 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 079 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 080 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 081 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 089 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 090 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 095 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 099 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 105 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 106 (DEM)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 110 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 113 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 117 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 118 (REP)',
 'NC HOUSE OF REPRESENTATIVES DISTRICT 119 (REP)',
 'NC STATE SENATE DISTRICT 01 (REP)',
 'NC STATE SENATE DISTRICT 05 (REP)',
 'NC STATE SENATE DISTRICT 09 (REP)',
 'NC STATE SENATE DISTRICT 10 (REP)',
 'NC STATE SENATE DISTRICT 12 (DEM)',
 'NC STATE SENATE DISTRICT 12 (REP)',
 'NC STATE SENATE DISTRICT 17 (REP)',
 'NC STATE SENATE DISTRICT 18 (REP)',
 'NC STATE SENATE DISTRICT 21 (REP)',
 'NC STATE SENATE DISTRICT 22 (DEM)',
 'NC STATE SENATE DISTRICT 26 (REP)',
 'NC STATE SENATE DISTRICT 30 (REP)',
 'NC STATE SENATE DISTRICT 32 (DEM)',
 'NC STATE SENATE DISTRICT 34 (REP)',
 'NC STATE SENATE DISTRICT 37 (DEM)',
 'NC SUPERIOR COURT JUDGE DISTRICT 16B SEAT 02 (DEM)',
 'NC SUPERIOR COURT JUDGE DISTRICT 26C SEAT 01 (DEM)',
 'NC SUPERIOR COURT JUDGE DISTRICT 36 SEAT 01 (REP)',
 'NEW HANOVER COUNTY BOARD OF COMMISSIONERS (DEM)',
 'NEW HANOVER COUNTY BOARD OF EDUCATION (DEM)',
 'NEW HANOVER COUNTY BOARD OF EDUCATION (REP)',
 'NEWTON-CONOVER SCHOOLS BOARD OF EDUCATION CONOVER DISTRICT (REP)',
 'NEWTON-CONOVER SCHOOLS BOARD OF EDUCATION NEWTON DISTRICT (REP)',
 'NORTHAMPTON COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (DEM)',
 'NORTHAMPTON COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (DEM)',
 'NORTHAMPTON COUNTY BOARD OF EDUCATION',
 'ONSLOW COUNTY BOARD OF COMMISSIONERS (REP)',
 'ONSLOW COUNTY BOARD OF EDUCATION (REP)',
 'ORANGE COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'ORANGE COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'ORANGE COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'ORANGE COUNTY REGISTER OF DEEDS (DEM)',
 'ORANGE COUNTY SCHOOLS BOARD OF EDUCATION',
 'ORANGE COUNTY SHERIFF (DEM)',
 'PAMLICO COUNTY BOARD OF COMMISSIONERS AT-LARGE (REP)',
 'PAMLICO COUNTY BOARD OF EDUCATION DISTRICT 04 (DEM)',
 'PASQUOTANK COUNTY CLERK OF SUPERIOR COURT (REP)',
 'PASQUOTANK COUNTY SHERIFF (REP)',
 'PENDER COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'PENDER COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'PENDER COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'PENDER COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (UNEXPIRED) (REP)',
 'PENDER COUNTY BOARD OF EDUCATION DISTRICT 01 (REP)',
 'PENDER COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'PENDER COUNTY CLERK OF SUPERIOR COURT (REP)',
 'PERQUIMANS COUNTY BOARD OF EDUCATION',
 'PERSON COUNTY BOARD OF COMMISSIONERS (REP)',
 'PERSON COUNTY BOARD OF COMMISSIONERS (UNEXPIRED) (REP)',
 'PERSON COUNTY SHERIFF (REP)',
 'PITT COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (DEM)',
 'PITT COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'PITT COUNTY BOARD OF COMMISSIONERS DISTRICT 06 (REP)',
 'PITT COUNTY SHERIFF (DEM)',
 'POLK COUNTY BOARD OF COMMISSIONERS (REP)',
 'POLK COUNTY SHERIFF (REP)',
 'RANDOLPH COUNTY BOARD OF COMMISSIONERS DISTRICT 03 (REP)',
 'RANDOLPH COUNTY SHERIFF (REP)',
 'RICHMOND COUNTY BOARD OF COMMISSIONERS (REP)',
 'RICHMOND COUNTY BOARD OF EDUCATION',
 'ROBESON COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (DEM)',
 'ROBESON COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (REP)',
 'ROBESON COUNTY BOARD OF COMMISSIONERS DISTRICT 08 (DEM)',
 'ROBESON COUNTY BOARD OF COMMISSIONERS DISTRICT 08 (REP)',
 'ROBESON COUNTY BOARD OF EDUCATION DISTRICT 02',
 'ROBESON COUNTY BOARD OF EDUCATION DISTRICT 03',
 'ROBESON COUNTY BOARD OF EDUCATION DISTRICT 06',
 'ROBESON COUNTY BOARD OF EDUCATION DISTRICT 08',
 'ROCKINGHAM COUNTY BOARD OF COMMISSIONERS (REP)',
 'ROCKINGHAM COUNTY BOARD OF EDUCATION AT-LARGE (REP)',
 'ROCKINGHAM COUNTY CLERK OF SUPERIOR COURT (REP)',
 'ROCKINGHAM COUNTY SHERIFF (DEM)',
 'ROCKINGHAM COUNTY SHERIFF (REP)',
 'ROWAN COUNTY BOARD OF COMMISSIONERS (REP)',
 'ROWAN COUNTY CLERK OF SUPERIOR COURT (REP)',
 'ROWAN COUNTY SHERIFF (REP)',
 'ROWAN-SALISBURY BOARD OF EDUCATION SEAT 04 (WEST) (REP)',
 'RUTHERFORD COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'RUTHERFORD COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (REP)',
 'RUTHERFORD COUNTY BOARD OF COMMISSIONERS DISTRICT 05 (REP)',
 'RUTHERFORD COUNTY BOARD OF EDUCATION DISTRICT 01 (DEM)',
 'RUTHERFORD COUNTY BOARD OF EDUCATION DISTRICT 01 (REP)',
 'RUTHERFORD COUNTY BOARD OF EDUCATION DISTRICT 02 (REP)',
 'RUTHERFORD COUNTY BOARD OF EDUCATION DISTRICT 03 (REP)',
 'RUTHERFORD COUNTY CLERK OF SUPERIOR COURT (REP)',
 'RUTHERFORD COUNTY SHERIFF (REP)',
 'SAMPSON COUNTY CLERK OF SUPERIOR COURT (REP)',
 'SAMPSON COUNTY SCHOOLS BOARD OF EDUCATION',
 'SAMPSON COUNTY SHERIFF (REP)',
 'SCOTLAND COUNTY BOARD OF COMMISSIONERS SPRING HILL TWP (REP)',
 'SCOTLAND COUNTY BOARD OF COMMISSIONERS STEWARTSVILLE TWP (REP)',
 'SCOTLAND COUNTY BOARD OF EDUCATION STEWARTSVILLE TWP (DEM)',
 'SCOTLAND COUNTY BOARD OF EDUCATION STEWARTSVILLE TWP (REP)',
 'SCOTLAND COUNTY CLERK OF SUPERIOR COURT (DEM)',
 'SCOTLAND COUNTY SHERIFF (REP)',
 'STANLY COUNTY BOARD OF COMMISSIONERS AT-LARGE (DEM)',
 'STANLY COUNTY BOARD OF COMMISSIONERS DISTRICT 01 (REP)',
 'STANLY COUNTY BOARD OF COMMISSIONERS DISTRICT 02 (REP)',
 'STANLY COUNTY BOARD OF COMMISSIONERS DISTRICT 04 (REP)',
 'STOKES COUNTY BOARD OF COMMISSIONERS (REP)',
 'STOKES COUNTY BOARD OF EDUCATION (REP)',
 'STOKES COUNTY SHERIFF (REP)',
 'SURRY COUNTY BOARD OF COMMISSIONERS CENTRAL DISTRICT (REP)',
 'SURRY COUNTY BOARD OF COMMISSIONERS MOUNT AIRY DISTRICT (REP)',
 'SURRY COUNTY CLERK OF SUPERIOR COURT (REP)',
 'SURRY COUNTY SCHOOLS BOARD OF EDUCATION DISTRICT 02 (REP)',

In [1125]:
contest_name = 'US SENATE (REP)'

In [1126]:
contest_df = results[results["Contest Name"] == contest_name]
contest_df

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,Early Voting,Absentee by Mail,Provisional,Total Votes,Real Precinct
4,BUNCOMBE,03/03/2026,20.1,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,0,1,0,0,1,Y
13,BUNCOMBE,03/03/2026,23.2,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,1,1,0,0,2,Y
20,BUNCOMBE,03/03/2026,24.1,2149,S,US SENATE (REP),Richard Dansie,REP,1,4,4,0,0,8,Y
25,BUNCOMBE,03/03/2026,26.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,2,0,0,0,2,Y
27,BUNCOMBE,03/03/2026,28.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,1,1,0,0,2,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103499,WARREN,03/03/2026,11,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y
103507,WASHINGTON,03/03/2026,LM,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,1,0,0,0,1,Y
103511,WASHINGTON,03/03/2026,P2,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,2,0,0,0,2,Y
103515,WASHINGTON,03/03/2026,SC,2149,S,US SENATE (REP),Michael Whatley,REP,1,57,0,0,0,57,Y
103516,WASHINGTON,03/03/2026,SK,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,18,0,0,0,18,Y

In [1127]:
# List of unique counties in chosen contest
contest_counties = contest_df["County"].unique()

In [1128]:
contest_counties

<StringArray>
[    'BUNCOMBE',     'CALDWELL',       'CAMDEN',     'CARTERET',
       'BLADEN',    'BRUNSWICK',     'BEAUFORT',       'BERTIE',
        'AVERY',        'BURKE',     'CABARRUS',      'FORSYTH',
    'GRANVILLE',       'GREENE',     'GUILFORD',     'FRANKLIN',
       'GASTON',   'MONTGOMERY',        'MOORE',         'PITT',
         'POLK',       'ONSLOW',       'ORANGE',   'PASQUOTANK',
       'PENDER',       'PERSON',     'JOHNSTON',        'JONES',
          'LEE',       'LENOIR',      'LINCOLN',  'MECKLENBURG',
     'MITCHELL',         'NASH',      'MADISON',       'MARTIN',
     'MCDOWELL',         'WAKE',       'WILSON',       'YADKIN',
       'YANCEY',        'UNION',        'VANCE',      'CASWELL',
      'CATAWBA',      'HAYWOOD',    'HENDERSON',      'HALIFAX',
      'HARNETT',       'GRAHAM',     'RANDOLPH',     'RICHMOND',
      'ROBESON',  'NEW HANOVER',        'WAYNE',       'WILKES',
      'WATAUGA',   'WASHINGTON',       'WARREN',      'TYRRELL',
      'CHATHAM',     'CHEROKEE',     'COLUMBUS',       'CRAVEN',
       'CHOWAN',      'IREDELL',      'JACKSON',      'SAMPSON',
   'ROCKINGHAM',        'ROWAN',        'SURRY',        'SWAIN',
      'PAMLICO',    'CLEVELAND',   'CUMBERLAND',     'DAVIDSON',
    'CURRITUCK',         'DARE',         'CLAY',        'MACON',
         'HYDE',   'PERQUIMANS',  'NORTHAMPTON',       'STOKES',
   'RUTHERFORD',        'DAVIE',       'DUPLIN',       'DURHAM',
     'HERTFORD',         'HOKE',     'SCOTLAND',       'STANLY',
    'EDGECOMBE', 'TRANSYLVANIA',         'ASHE',     'ALAMANCE',
        'GATES',        'ANSON',    'ALEXANDER',    'ALLEGHANY']
Length: 100, dtype: str

In [1129]:
# Now, filter the election results. First by "Real Precinct" == Y. 
# We will only map Real Precincts. See notes for data definitions.
contest_results_geo_df = contest_df[contest_df["Real Precinct"] == "Y"].copy()

In [1130]:
contest_results_geo_df.shape

(18431, 15)

In [1131]:
# Number of unique pairs of precincts and counties
# Different counties can share the same precinct ids e.g. Durham county, precinct 21 & Chatham county, precinct 21
# So we check for unique pairs
unique_pair_counts = contest_results_geo_df[['County', 'Precinct']].value_counts()

In [1132]:
unique_pair_counts

County       Precinct
BUNCOMBE     20.1        7
             23.2        7
             24.1        7
             26.1        7
             28.1        7
                        ..
ASHE         16          7
GUILFORD     H24         7
NORTHAMPTON  LAKE G      7
FORSYTH      14          7
ASHE         9           7
Name: count, Length: 2633, dtype: int64

In [1133]:
# Note: counts for each precinct should match the number of candidates in the contest
# Contest results data is one row per candidate in each precinct. We will group by precinct further below
# Validate manually using google spreadsheet
unique_pair_counts.groupby("County").size()

County
ALAMANCE     39
ALEXANDER    10
ALLEGHANY     4
ANSON         9
ASHE         17
             ..
WAYNE        28
WILKES       25
WILSON       24
YADKIN       12
YANCEY       11
Name: count, Length: 100, dtype: int64

### Get total votes for each candidate at the contest-level

In [1134]:
candidate_summary = (
    contest_results_geo_df
    .groupby("Choice", as_index=False)["Total Votes"]
    .sum()
    .rename(columns={
        "Choice": "candidate",
        "Total Votes": "votes"
    })
)

In [1135]:
candidate_summary["share"] = (
    candidate_summary["votes"]
    / candidate_summary["votes"].sum()
    * 100
)

In [1136]:
candidate_summary

               candidate   votes      share
0  Donald M. (Don) Brown   82382  15.626683
1    Elizabeth A. Temple   20047   3.802628
2           Margot Dupre   12417   2.355327
3        Michael Whatley  340816  64.647905
4         Michele Morrow   29371   5.571257
5         Richard Dansie   12654   2.400282
6         Thomas Johnson   29501   5.595916

In [1137]:
output_file_path = os.path.join(script_dir, '..', 'data', 'processed', f'{pydash.snake_case(contest_name)}_contest_candidate_summary.csv')

In [1138]:
candidate_summary.to_csv(output_file_path, index=False)

## Summarize contest results for MapBox

We will calculate and label results for our maps.
- Create a unique id from county and precincts
- Total votes in contest per precinct
- Winner
- Runner-up
- Margin of victory points
- Margin of victory percentage
- Each candidates vote share percentage
- Et. al.

In [1139]:
# Counts for each candidate represents the number of precincts that participated in the contest
# Validate with pair_counts
contest_results_geo_df["Choice"].value_counts()

Choice
Elizabeth A. Temple      2633
Donald M. (Don) Brown    2633
Richard Dansie           2633
Thomas Johnson           2633
Michael Whatley          2633
Michele Morrow           2633
Margot Dupre             2633
Name: count, dtype: int64

In [1140]:
# Check if Total Votes has any missing values i.e. precincts that did not participate
contest_results_geo_df["Total Votes"].isna().sum()

np.int64(0)

In [1142]:
contest_results_geo_df[contest_results_geo_df["Total Votes"] == 0]

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,Early Voting,Absentee by Mail,Provisional,Total Votes,Real Precinct
250,BERTIE,03/03/2026,SN,2149,S,US SENATE (REP),Michele Morrow,REP,1,0,0,0,0,0,Y
262,BLADEN,03/03/2026,P10,2149,S,US SENATE (REP),Richard Dansie,REP,1,0,0,0,0,0,Y
297,BUNCOMBE,03/03/2026,34.1,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y
607,FORSYTH,03/03/2026,205,2149,S,US SENATE (REP),Richard Dansie,REP,1,0,0,0,0,0,Y
650,GREENE,03/03/2026,BEAR,2149,S,US SENATE (REP),Thomas Johnson,REP,1,0,0,0,0,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103033,TYRRELL,03/03/2026,14,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,0,0,0,0,0,Y
103037,TYRRELL,03/03/2026,16,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,0,0,0,0,0,Y
103155,WAKE,03/03/2026,01-19,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y
103185,WAKE,03/03/2026,01-41,2149,S,US SENATE (REP),Richard Dansie,REP,1,0,0,0,0,0,Y
103499,WARREN,03/03/2026,11,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y

In [1141]:
# Check if Total Votes is numeric
contest_results_geo_df["Total Votes"].dtype

dtype('int64')

### Create a unique id from precinct id and county name
Precinct ids are not truly unique. Different counties can have the same id e.g. Durham and Chatham both have precinct 15

In [1143]:
contest_results_geo_df["County"].dtype

In [1144]:
contest_results_geo_df["Precinct"].dtype

In [1145]:
contest_results_geo_df["county_precinct"] = contest_results_geo_df["County"] + '_' + contest_results_geo_df["Precinct"]

In [1146]:
contest_results_geo_df

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,Early Voting,Absentee by Mail,Provisional,Total Votes,Real Precinct,county_precinct
4,BUNCOMBE,03/03/2026,20.1,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,0,1,0,0,1,Y,BUNCOMBE_20.1
13,BUNCOMBE,03/03/2026,23.2,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,1,1,0,0,2,Y,BUNCOMBE_23.2
20,BUNCOMBE,03/03/2026,24.1,2149,S,US SENATE (REP),Richard Dansie,REP,1,4,4,0,0,8,Y,BUNCOMBE_24.1
25,BUNCOMBE,03/03/2026,26.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,2,0,0,0,2,Y,BUNCOMBE_26.1
27,BUNCOMBE,03/03/2026,28.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,1,1,0,0,2,Y,BUNCOMBE_28.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103499,WARREN,03/03/2026,11,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y,WARREN_11
103507,WASHINGTON,03/03/2026,LM,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,1,0,0,0,1,Y,WASHINGTON_LM
103511,WASHINGTON,03/03/2026,P2,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,2,0,0,0,2,Y,WASHINGTON_P2
103515,WASHINGTON,03/03/2026,SC,2149,S,US SENATE (REP),Michael Whatley,REP,1,57,0,0,0,57,Y,WASHINGTON_SC
103516,WASHINGTON,03/03/2026,SK,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,18,0,0,0,18,Y,WASHINGTON_SK

### Get total votes casted in each precinct

In [1147]:
# Calculate total votes cast in each precinct
precinct_totals = (
    contest_results_geo_df
    .groupby("county_precinct")["Total Votes"]
    .sum()
    .rename("contest_votes")
)

In [1148]:
precinct_totals

county_precinct
ALAMANCE_03C     416
ALAMANCE_03N     354
ALAMANCE_03N2    129
ALAMANCE_03SE    339
ALAMANCE_03SM    310
                ...
YANCEY_07 BRU     60
YANCEY_08 CRA    299
YANCEY_09 SOU    191
YANCEY_10 PEN     89
YANCEY_11 PRI    223
Name: contest_votes, Length: 2633, dtype: int64

In [1149]:
contest_results_geo_df = contest_results_geo_df.merge(
    precinct_totals,
    on="county_precinct",
    how="left"
)

In [1150]:
contest_results_geo_df

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,Early Voting,Absentee by Mail,Provisional,Total Votes,Real Precinct,county_precinct,contest_votes
0,BUNCOMBE,03/03/2026,20.1,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,0,1,0,0,1,Y,BUNCOMBE_20.1,27
1,BUNCOMBE,03/03/2026,23.2,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,1,1,0,0,2,Y,BUNCOMBE_23.2,23
2,BUNCOMBE,03/03/2026,24.1,2149,S,US SENATE (REP),Richard Dansie,REP,1,4,4,0,0,8,Y,BUNCOMBE_24.1,124
3,BUNCOMBE,03/03/2026,26.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,2,0,0,0,2,Y,BUNCOMBE_26.1,38
4,BUNCOMBE,03/03/2026,28.1,2149,S,US SENATE (REP),Thomas Johnson,REP,1,1,1,0,0,2,Y,BUNCOMBE_28.1,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18426,WARREN,03/03/2026,11,2149,S,US SENATE (REP),Margot Dupre,REP,1,0,0,0,0,0,Y,WARREN_11,18
18427,WASHINGTON,03/03/2026,LM,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,1,0,0,0,1,Y,WASHINGTON_LM,66
18428,WASHINGTON,03/03/2026,P2,2149,S,US SENATE (REP),Elizabeth A. Temple,REP,1,2,0,0,0,2,Y,WASHINGTON_P2,27
18429,WASHINGTON,03/03/2026,SC,2149,S,US SENATE (REP),Michael Whatley,REP,1,57,0,0,0,57,Y,WASHINGTON_SC,86
18430,WASHINGTON,03/03/2026,SK,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,18,0,0,0,18,Y,WASHINGTON_SK,78

### Summarize the contest results
Identify the winner and runner-up in each precinct. Then, create a new dataframe with one precinct per row for MapBox.

In [1151]:
contest_results_geo_df.rename(columns={"Total Votes": "candidate_votes"}, inplace=True)

In [1152]:
ranked = contest_results_geo_df.sort_values(["county_precinct", "candidate_votes"], ascending=[True, False]).copy()

In [1153]:
# Add rankings
ranked["rank"] = (
    ranked.groupby("county_precinct").cumcount() + 1
)

In [1154]:
first_second_df = ranked[ranked["rank"].isin([1,2])].copy()

In [1155]:
first_second_df

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,Early Voting,Absentee by Mail,Provisional,candidate_votes,Real Precinct,county_precinct,contest_votes,rank
2224,ALAMANCE,03/03/2026,03C,2149,S,US SENATE (REP),Michael Whatley,REP,1,188,96,5,0,289,Y,ALAMANCE_03C,416,1
6897,ALAMANCE,03/03/2026,03C,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,31,7,0,0,38,Y,ALAMANCE_03C,416,2
2210,ALAMANCE,03/03/2026,03N,2149,S,US SENATE (REP),Michael Whatley,REP,1,147,96,5,0,248,Y,ALAMANCE_03N,354,1
2174,ALAMANCE,03/03/2026,03N,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,25,9,0,0,34,Y,ALAMANCE_03N,354,2
8084,ALAMANCE,03/03/2026,03N2,2149,S,US SENATE (REP),Michael Whatley,REP,1,76,13,0,0,89,Y,ALAMANCE_03N2,129,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,YANCEY,03/03/2026,09 SOU,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,13,9,0,0,22,Y,YANCEY_09 SOU,191,2
17690,YANCEY,03/03/2026,10 PEN,2149,S,US SENATE (REP),Michael Whatley,REP,1,45,22,0,0,67,Y,YANCEY_10 PEN,89,1
18043,YANCEY,03/03/2026,10 PEN,2149,S,US SENATE (REP),Michele Morrow,REP,1,4,4,0,0,8,Y,YANCEY_10 PEN,89,2
14904,YANCEY,03/03/2026,11 PRI,2149,S,US SENATE (REP),Michael Whatley,REP,1,63,86,0,0,149,Y,YANCEY_11 PRI,223,1
980,YANCEY,03/03/2026,11 PRI,2149,S,US SENATE (REP),Donald M. (Don) Brown,REP,1,8,12,0,0,20,Y,YANCEY_11 PRI,223,2

In [1156]:
winner_df = (
    first_second_df[first_second_df["rank"] == 1]
        [["Contest Name", "County", "Precinct", "county_precinct", "contest_votes", "Choice", "candidate_votes"]].rename(columns={
        "Choice": "winner",
        "candidate_votes": "winner_votes"
    })
)

In [1157]:
winner_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes
2224,US SENATE (REP),ALAMANCE,03C,ALAMANCE_03C,416,Michael Whatley,289
2210,US SENATE (REP),ALAMANCE,03N,ALAMANCE_03N,354,Michael Whatley,248
8084,US SENATE (REP),ALAMANCE,03N2,ALAMANCE_03N2,129,Michael Whatley,89
2193,US SENATE (REP),ALAMANCE,03SE,ALAMANCE_03SE,339,Michael Whatley,252
6861,US SENATE (REP),ALAMANCE,03SM,ALAMANCE_03SM,310,Michael Whatley,193
...,...,...,...,...,...,...,...
9898,US SENATE (REP),YANCEY,07 BRU,YANCEY_07 BRU,60,Michael Whatley,38
12988,US SENATE (REP),YANCEY,08 CRA,YANCEY_08 CRA,299,Michael Whatley,194
12990,US SENATE (REP),YANCEY,09 SOU,YANCEY_09 SOU,191,Michael Whatley,119
17690,US SENATE (REP),YANCEY,10 PEN,YANCEY_10 PEN,89,Michael Whatley,67
14904,US SENATE (REP),YANCEY,11 PRI,YANCEY_11 PRI,223,Michael Whatley,149

In [1158]:
runner_up_df = (
    first_second_df[first_second_df["rank"] == 2]
        [["county_precinct", "Choice", "candidate_votes"]].rename(columns={
        "Choice": "runner_up",
        "candidate_votes": "runner_up_votes"
    })
)

In [1159]:
runner_up_df

      county_precinct              runner_up  runner_up_votes
6897     ALAMANCE_03C  Donald M. (Don) Brown               38
2174     ALAMANCE_03N  Donald M. (Don) Brown               34
2211    ALAMANCE_03N2  Donald M. (Don) Brown               15
6822    ALAMANCE_03SE  Donald M. (Don) Brown               27
6868    ALAMANCE_03SM  Donald M. (Don) Brown               51
...               ...                    ...              ...
14869   YANCEY_07 BRU         Michele Morrow                6
14902   YANCEY_08 CRA  Donald M. (Don) Brown               35
672     YANCEY_09 SOU  Donald M. (Don) Brown               22
18043   YANCEY_10 PEN         Michele Morrow                8
980     YANCEY_11 PRI  Donald M. (Don) Brown               20

[2633 rows x 3 columns]

In [1160]:
contest_summary_df = winner_df.merge(
    runner_up_df,
    on="county_precinct",
    how="left"
)

In [1161]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes
0,US SENATE (REP),ALAMANCE,03C,ALAMANCE_03C,416,Michael Whatley,289,Donald M. (Don) Brown,38
1,US SENATE (REP),ALAMANCE,03N,ALAMANCE_03N,354,Michael Whatley,248,Donald M. (Don) Brown,34
2,US SENATE (REP),ALAMANCE,03N2,ALAMANCE_03N2,129,Michael Whatley,89,Donald M. (Don) Brown,15
3,US SENATE (REP),ALAMANCE,03SE,ALAMANCE_03SE,339,Michael Whatley,252,Donald M. (Don) Brown,27
4,US SENATE (REP),ALAMANCE,03SM,ALAMANCE_03SM,310,Michael Whatley,193,Donald M. (Don) Brown,51
...,...,...,...,...,...,...,...,...,...
2628,US SENATE (REP),YANCEY,07 BRU,YANCEY_07 BRU,60,Michael Whatley,38,Michele Morrow,6
2629,US SENATE (REP),YANCEY,08 CRA,YANCEY_08 CRA,299,Michael Whatley,194,Donald M. (Don) Brown,35
2630,US SENATE (REP),YANCEY,09 SOU,YANCEY_09 SOU,191,Michael Whatley,119,Donald M. (Don) Brown,22
2631,US SENATE (REP),YANCEY,10 PEN,YANCEY_10 PEN,89,Michael Whatley,67,Michele Morrow,8
2632,US SENATE (REP),YANCEY,11 PRI,YANCEY_11 PRI,223,Michael Whatley,149,Donald M. (Don) Brown,20

### Calculate vote shares for winner and runner-up
Vote Share: the percentage of total votes cast that a specific political party or candidate receives in an election.

In [1162]:
contest_summary_df["winner_vote_share"] = (
    (contest_summary_df["winner_votes"] /
    contest_summary_df["contest_votes"]) * 100
)

In [1163]:
contest_summary_df["runner_up_vote_share"] = (
    (contest_summary_df["runner_up_votes"] /
    contest_summary_df["contest_votes"]) * 100
)

In [1164]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share
0,US SENATE (REP),ALAMANCE,03C,ALAMANCE_03C,416,Michael Whatley,289,Donald M. (Don) Brown,38,69.471154,9.134615
1,US SENATE (REP),ALAMANCE,03N,ALAMANCE_03N,354,Michael Whatley,248,Donald M. (Don) Brown,34,70.056497,9.604520
2,US SENATE (REP),ALAMANCE,03N2,ALAMANCE_03N2,129,Michael Whatley,89,Donald M. (Don) Brown,15,68.992248,11.627907
3,US SENATE (REP),ALAMANCE,03SE,ALAMANCE_03SE,339,Michael Whatley,252,Donald M. (Don) Brown,27,74.336283,7.964602
4,US SENATE (REP),ALAMANCE,03SM,ALAMANCE_03SM,310,Michael Whatley,193,Donald M. (Don) Brown,51,62.258065,16.451613
...,...,...,...,...,...,...,...,...,...,...,...
2628,US SENATE (REP),YANCEY,07 BRU,YANCEY_07 BRU,60,Michael Whatley,38,Michele Morrow,6,63.333333,10.000000
2629,US SENATE (REP),YANCEY,08 CRA,YANCEY_08 CRA,299,Michael Whatley,194,Donald M. (Don) Brown,35,64.882943,11.705686
2630,US SENATE (REP),YANCEY,09 SOU,YANCEY_09 SOU,191,Michael Whatley,119,Donald M. (Don) Brown,22,62.303665,11.518325
2631,US SENATE (REP),YANCEY,10 PEN,YANCEY_10 PEN,89,Michael Whatley,67,Michele Morrow,8,75.280899,8.988764
2632,US SENATE (REP),YANCEY,11 PRI,YANCEY_11 PRI,223,Michael Whatley,149,Donald M. (Don) Brown,20,66.816143,8.968610

### Calculate margin of victory
MOV: Difference between the vote share of the winning candidate and the second-place candidate. 

For example, if Candidate A wins with 55% of the vote and Candidate B receives 45%, the margin of victory is 10 percentage points.

In [1165]:
contest_summary_df["margin_of_victory"] = (
    contest_summary_df["winner_vote_share"] - contest_summary_df["runner_up_vote_share"]
)

In [1166]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory
0,US SENATE (REP),ALAMANCE,03C,ALAMANCE_03C,416,Michael Whatley,289,Donald M. (Don) Brown,38,69.471154,9.134615,60.336538
1,US SENATE (REP),ALAMANCE,03N,ALAMANCE_03N,354,Michael Whatley,248,Donald M. (Don) Brown,34,70.056497,9.604520,60.451977
2,US SENATE (REP),ALAMANCE,03N2,ALAMANCE_03N2,129,Michael Whatley,89,Donald M. (Don) Brown,15,68.992248,11.627907,57.364341
3,US SENATE (REP),ALAMANCE,03SE,ALAMANCE_03SE,339,Michael Whatley,252,Donald M. (Don) Brown,27,74.336283,7.964602,66.371681
4,US SENATE (REP),ALAMANCE,03SM,ALAMANCE_03SM,310,Michael Whatley,193,Donald M. (Don) Brown,51,62.258065,16.451613,45.806452
...,...,...,...,...,...,...,...,...,...,...,...,...
2628,US SENATE (REP),YANCEY,07 BRU,YANCEY_07 BRU,60,Michael Whatley,38,Michele Morrow,6,63.333333,10.000000,53.333333
2629,US SENATE (REP),YANCEY,08 CRA,YANCEY_08 CRA,299,Michael Whatley,194,Donald M. (Don) Brown,35,64.882943,11.705686,53.177258
2630,US SENATE (REP),YANCEY,09 SOU,YANCEY_09 SOU,191,Michael Whatley,119,Donald M. (Don) Brown,22,62.303665,11.518325,50.785340
2631,US SENATE (REP),YANCEY,10 PEN,YANCEY_10 PEN,89,Michael Whatley,67,Michele Morrow,8,75.280899,8.988764,66.292135
2632,US SENATE (REP),YANCEY,11 PRI,YANCEY_11 PRI,223,Michael Whatley,149,Donald M. (Don) Brown,20,66.816143,8.968610,57.847534

### Get results for all candidates for each precinct

In [1169]:
def calc_vote_share(candidate_votes, contest_votes):
    if contest_votes > 0:
        return float((candidate_votes / contest_votes) * 100)
    if contest_votes == 0:
        return 0

In [1170]:
all_candidate_results = (
    contest_results_geo_df
    .sort_values(["county_precinct", "candidate_votes"], ascending=[True, False])
    .groupby("county_precinct")
    .apply(
        lambda g: [
            {
                "candidate": row["Choice"],
                "votes": int(row["candidate_votes"]),
                "share": calc_vote_share(row["candidate_votes"], row["contest_votes"])
            }
            for _, row in g.iterrows()
        ],
        include_groups=False
    )
)

In [1171]:
all_candidate_results

county_precinct
ALAMANCE_03C     [{'candidate': 'Michael Whatley', 'votes': 289...
ALAMANCE_03N     [{'candidate': 'Michael Whatley', 'votes': 248...
ALAMANCE_03N2    [{'candidate': 'Michael Whatley', 'votes': 89,...
ALAMANCE_03SE    [{'candidate': 'Michael Whatley', 'votes': 252...
ALAMANCE_03SM    [{'candidate': 'Michael Whatley', 'votes': 193...
                                       ...
YANCEY_07 BRU    [{'candidate': 'Michael Whatley', 'votes': 38,...
YANCEY_08 CRA    [{'candidate': 'Michael Whatley', 'votes': 194...
YANCEY_09 SOU    [{'candidate': 'Michael Whatley', 'votes': 119...
YANCEY_10 PEN    [{'candidate': 'Michael Whatley', 'votes': 67,...
YANCEY_11 PRI    [{'candidate': 'Michael Whatley', 'votes': 149...
Length: 2633, dtype: object

In [1172]:
contest_summary_df[contest_summary_df["county_precinct"] == "WAKE_12-08"]

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory
2406,US SENATE (REP),WAKE,12-08,WAKE_12-08,155,Michael Whatley,104,Donald M. (Don) Brown,25,67.096774,16.129032,50.967742

In [1174]:
contest_summary_df["all_candidate_results"] = contest_summary_df["county_precinct"].map(all_candidate_results)

In [1175]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results
0,US SENATE (REP),ALAMANCE,03C,ALAMANCE_03C,416,Michael Whatley,289,Donald M. (Don) Brown,38,69.471154,9.134615,60.336538,"[{'candidate': 'Michael Whatley', 'votes': 289..."
1,US SENATE (REP),ALAMANCE,03N,ALAMANCE_03N,354,Michael Whatley,248,Donald M. (Don) Brown,34,70.056497,9.604520,60.451977,"[{'candidate': 'Michael Whatley', 'votes': 248..."
2,US SENATE (REP),ALAMANCE,03N2,ALAMANCE_03N2,129,Michael Whatley,89,Donald M. (Don) Brown,15,68.992248,11.627907,57.364341,"[{'candidate': 'Michael Whatley', 'votes': 89,..."
3,US SENATE (REP),ALAMANCE,03SE,ALAMANCE_03SE,339,Michael Whatley,252,Donald M. (Don) Brown,27,74.336283,7.964602,66.371681,"[{'candidate': 'Michael Whatley', 'votes': 252..."
4,US SENATE (REP),ALAMANCE,03SM,ALAMANCE_03SM,310,Michael Whatley,193,Donald M. (Don) Brown,51,62.258065,16.451613,45.806452,"[{'candidate': 'Michael Whatley', 'votes': 193..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2628,US SENATE (REP),YANCEY,07 BRU,YANCEY_07 BRU,60,Michael Whatley,38,Michele Morrow,6,63.333333,10.000000,53.333333,"[{'candidate': 'Michael Whatley', 'votes': 38,..."
2629,US SENATE (REP),YANCEY,08 CRA,YANCEY_08 CRA,299,Michael Whatley,194,Donald M. (Don) Brown,35,64.882943,11.705686,53.177258,"[{'candidate': 'Michael Whatley', 'votes': 194..."
2630,US SENATE (REP),YANCEY,09 SOU,YANCEY_09 SOU,191,Michael Whatley,119,Donald M. (Don) Brown,22,62.303665,11.518325,50.785340,"[{'candidate': 'Michael Whatley', 'votes': 119..."
2631,US SENATE (REP),YANCEY,10 PEN,YANCEY_10 PEN,89,Michael Whatley,67,Michele Morrow,8,75.280899,8.988764,66.292135,"[{'candidate': 'Michael Whatley', 'votes': 67,..."
2632,US SENATE (REP),YANCEY,11 PRI,YANCEY_11 PRI,223,Michael Whatley,149,Donald M. (Don) Brown,20,66.816143,8.968610,57.847534,"[{'candidate': 'Michael Whatley', 'votes': 149..."

In [1180]:
contest_summary_df[contest_summary_df['contest_votes'] == 0]

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results
705,US SENATE (REP),DURHAM,12,DURHAM_12,0,Michele Morrow,0,Michael Whatley,0,NaN,NaN,NaN,"[{'candidate': 'Michele Morrow', 'votes': 0, '..."
740,US SENATE (REP),DURHAM,41,DURHAM_41,0,Michael Whatley,0,Margot Dupre,0,NaN,NaN,NaN,"[{'candidate': 'Michael Whatley', 'votes': 0, ..."
754,US SENATE (REP),DURHAM,55-49,DURHAM_55-49,0,Michael Whatley,0,Richard Dansie,0,NaN,NaN,NaN,"[{'candidate': 'Michael Whatley', 'votes': 0, ..."
768,US SENATE (REP),EDGECOMBE,1202,EDGECOMBE_1202,0,Michael Whatley,0,Donald M. (Don) Brown,0,NaN,NaN,NaN,"[{'candidate': 'Michael Whatley', 'votes': 0, ..."
806,US SENATE (REP),FORSYTH,301,FORSYTH_301,0,Donald M. (Don) Brown,0,Elizabeth A. Temple,0,NaN,NaN,NaN,"[{'candidate': 'Donald M. (Don) Brown', 'votes..."
808,US SENATE (REP),FORSYTH,303,FORSYTH_303,0,Elizabeth A. Temple,0,Michele Morrow,0,NaN,NaN,NaN,"[{'candidate': 'Elizabeth A. Temple', 'votes':..."
1066,US SENATE (REP),GUILFORD,G68,GUILFORD_G68,0,Thomas Johnson,0,Michael Whatley,0,NaN,NaN,NaN,"[{'candidate': 'Thomas Johnson', 'votes': 0, '..."
1622,US SENATE (REP),MECKLENBURG,56,MECKLENBURG_56,0,Michele Morrow,0,Richard Dansie,0,NaN,NaN,NaN,"[{'candidate': 'Michele Morrow', 'votes': 0, '..."
2097,US SENATE (REP),SAMPSON,CLCE,SAMPSON_CLCE,0,Richard Dansie,0,Elizabeth A. Temple,0,NaN,NaN,NaN,"[{'candidate': 'Richard Dansie', 'votes': 0, '..."
2098,US SENATE (REP),SAMPSON,CLEA,SAMPSON_CLEA,0,Thomas Johnson,0,Richard Dansie,0,NaN,NaN,NaN,"[{'candidate': 'Thomas Johnson', 'votes': 0, '..."
2100,US SENATE (REP),SAMPSON,CLNE,SAMPSON_CLNE,0,Donald M. (Don) Brown,0,Michele Morrow,0,NaN,NaN,NaN,"[{'candidate': 'Donald M. (Don) Brown', 'votes..."
2101,US SENATE (REP),SAMPSON,CLSW,SAMPSON_CLSW,0,Donald M. (Don) Brown,0,Richard Dansie,0,NaN,NaN,NaN,"[{'candidate': 'Donald M. (Don) Brown', 'votes..."
2102,US SENATE (REP),SAMPSON,CLWE,SAMPSON_CLWE,0,Richard Dansie,0,Michael Whatley,0,NaN,NaN,NaN,"[{'candidate': 'Richard Dansie', 'votes': 0, '..."
2109,US SENATE (REP),SAMPSON,KFRK,SAMPSON_KFRK,0,Donald M. (Don) Brown,0,Thomas Johnson,0,NaN,NaN,NaN,"[{'candidate': 'Donald M. (Don) Brown', 'votes..."
2115,US SENATE (REP),SAMPSON,ROWA,SAMPSON_ROWA,0,Margot Dupre,0,Michael Whatley,0,NaN,NaN,NaN,"[{'candidate': 'Margot Dupre', 'votes': 0, 'sh..."
2211,US SENATE (REP),TYRRELL,16,TYRRELL_16,0,Michele Morrow,0,Richard Dansie,0,NaN,NaN,NaN,"[{'candidate': 'Michele Morrow', 'votes': 0, '..."

In [1181]:
# Needed for crosswalk right now. Will eventually reorganize files

In [1177]:
output_file_path = os.path.join(script_dir, '..', 'data', 'processed', f'{pydash.snake_case(contest_name)}_contest_summary.csv')

In [1178]:
contest_summary_df.to_csv(output_file_path, index=False)

### Calculate Opacity if needed

### Bring in precinct shape file and merge with our contest's summary data
Results should produce a geodataframe with geometry for each precinct

In [1092]:
shp_file_path = os.path.join(script_dir, '..', 'data', 'raw', 'geography', 'SBE_PRECINCTS_20251212', 'SBE_PRECINCTS_20251212.shp')

In [1093]:
precincts_gdf = gpd.read_file(shp_file_path)

In [1094]:
# Filter precinct GeoDataFrame by counties in the chosen contest
contest_precincts_gdf = precincts[precincts["county_nam"].isin(contest_counties)]

In [1095]:
contest_precincts_gdf

,id,county_id,prec_id,enr_desc,county_nam,Shape_Leng,Shape_Area,of_prec_id,geometry
59,105,92,01-05,01-05,WAKE,14500.105940,1.325901e+07,NaN,"POLYGON ((2104962.991 746518.459, 2104960.007 ..."
71,110,92,01-09,01-09,WAKE,12038.234692,8.161909e+06,NaN,"POLYGON ((2106835.489 746138.993, 2106712.756 ..."
114,99,92,01-01,01-01,WAKE,16835.331171,1.549578e+07,NaN,"POLYGON ((2100440.458 741338.285, 2100440.556 ..."
116,101,92,01-02,01-02,WAKE,24437.015415,2.445547e+07,NaN,"POLYGON ((2096969.047 743377.041, 2096967.151 ..."
117,102,92,01-03,01-03,WAKE,21790.186717,2.242057e+07,NaN,"POLYGON ((2096391.936 746636.928, 2096320.174 ..."
...,...,...,...,...,...,...,...,...,...
2623,3141,92,13-12,13-12,WAKE,40066.315909,4.649720e+07,NaN,"POLYGON ((2121521.829 766440.325, 2121587.911 ..."
2624,3142,92,12-12,12-12,WAKE,46001.066465,8.927364e+07,NaN,"POLYGON ((2074291.413 679114.557, 2074060.621 ..."
2625,3143,92,12-13,12-13,WAKE,50225.930446,1.275286e+08,NaN,"POLYGON ((2067423.477 669347.8, 2067409.868 66..."
2626,3144,92,05-09,05-09,WAKE,26574.404656,4.180295e+07,NaN,"POLYGON ((2047460.895 752794.873, 2047335.208 ..."
2627,3145,92,05-10,05-10,WAKE,54128.846329,1.145843e+08,NaN,"POLYGON ((2037950.618 753669.957, 2037929.585 ..."

In [1096]:
# Number of rows = number of all precincts in contest counties
# Note: not all precincts in the entire county participate in every contest
contest_precincts_gdf.shape

(231, 9)

In [1097]:
contest_precincts_gdf["county_nam"].unique()

<StringArray>
['WAKE', 'GRANVILLE']
Length: 2, dtype: str

In [98]:
# Note: not all precincts in each county participate in certain contests
# e.g. US House of Represenetatives District 04 (Dem) includes some but not all of Wake and Chatham

In [102]:
# Note: Some precincts need format cleaning.
# e.g. Durham has precincts 01-09. On the precinct geo file, these precinct ids are 01-09. 
# On the election results data, these precinct ids are 1-9
# Precinct ids must match in order to join both data sets. Otherwise mismatches will occur and votes count will be inaccuracy

In [1098]:
# Function to normalize the 1 and 01 precinct id issue in Durham

def normalize_precinct_id(x):
    x = str(x).strip()

    if x.isdigit():
        return x.zfill(2)

    return x

In [1099]:
# We will make a new column on both dfs that creates a normalized two digit precinct id
# i.e. both will have precinct ids "01", "02", etc.
# The function above also account for precincts that are alpha characters i.e. Orange County
contest_precincts_gdf["precinct_join"] = contest_precincts_gdf["prec_id"]

contest_summary_df["precinct_join"] = contest_summary_df["Precinct"].apply(
    normalize_precinct_id
)

In [1100]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results,precinct_join
0,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,ANTI,GRANVILLE_ANTI,101,Chris Stock,63,Cheryl Caulfield,38,62.376238,37.623762,24.752475,"[{'candidate': 'Chris Stock', 'votes': 63, 'sh...",ANTI
1,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,BERE,GRANVILLE_BERE,240,Chris Stock,167,Cheryl Caulfield,73,69.583333,30.416667,39.166667,"[{'candidate': 'Chris Stock', 'votes': 167, 's...",BERE
2,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,BTNR,GRANVILLE_BTNR,218,Chris Stock,161,Cheryl Caulfield,57,73.853211,26.146789,47.706422,"[{'candidate': 'Chris Stock', 'votes': 161, 's...",BTNR
3,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CORI,GRANVILLE_CORI,306,Chris Stock,202,Cheryl Caulfield,104,66.013072,33.986928,32.026144,"[{'candidate': 'Chris Stock', 'votes': 202, 's...",CORI
4,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CRDL,GRANVILLE_CRDL,107,Chris Stock,75,Cheryl Caulfield,32,70.093458,29.906542,40.186916,"[{'candidate': 'Chris Stock', 'votes': 75, 'sh...",CRDL
5,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CRDM,GRANVILLE_CRDM,472,Chris Stock,332,Cheryl Caulfield,140,70.338983,29.661017,40.677966,"[{'candidate': 'Chris Stock', 'votes': 332, 's...",CRDM
6,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,EAOX,GRANVILLE_EAOX,135,Chris Stock,104,Cheryl Caulfield,31,77.037037,22.962963,54.074074,"[{'candidate': 'Chris Stock', 'votes': 104, 's...",EAOX
7,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,MTEN,GRANVILLE_MTEN,579,Chris Stock,391,Cheryl Caulfield,188,67.530225,32.469775,35.060449,"[{'candidate': 'Chris Stock', 'votes': 391, 's...",MTEN
8,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,OKHL,GRANVILLE_OKHL,163,Chris Stock,111,Cheryl Caulfield,52,68.098160,31.901840,36.196319,"[{'candidate': 'Chris Stock', 'votes': 111, 's...",OKHL
9,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SALM,GRANVILLE_SALM,234,Chris Stock,166,Cheryl Caulfield,68,70.940171,29.059829,41.880342,"[{'candidate': 'Chris Stock', 'votes': 166, 's...",SALM
10,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SASS,GRANVILLE_SASS,277,Chris Stock,201,Cheryl Caulfield,76,72.563177,27.436823,45.126354,"[{'candidate': 'Chris Stock', 'votes': 201, 's...",SASS
11,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SOOX,GRANVILLE_SOOX,77,Chris Stock,64,Cheryl Caulfield,13,83.116883,16.883117,66.233766,"[{'candidate': 'Chris Stock', 'votes': 64, 'sh...",SOOX
12,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,TYHO,GRANVILLE_TYHO,631,Chris Stock,476,Cheryl Caulfield,155,75.435816,24.564184,50.871632,"[{'candidate': 'Chris Stock', 'votes': 476, 's...",TYHO
13,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,WILT,GRANVILLE_WILT,846,Chris Stock,551,Cheryl Caulfield,295,65.130024,34.869976,30.260047,"[{'candidate': 'Chris Stock', 'votes': 551, 's...",WILT
14,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,WOEL,GRANVILLE_WOEL,116,Chris Stock,86,Cheryl Caulfield,30,74.137931,25.862069,48.275862,"[{'candidate': 'Chris Stock', 'votes': 86, 'sh...",WOEL
15,NC STATE SENATE DISTRICT 18 (REP),WAKE,01-42,WAKE_01-42,154,Chris Stock,80,Cheryl Caulfield,74,51.948052,48.051948,3.896104,"[{'candidate': 'Chris Stock', 'votes': 80, 'sh...",01-42
16,NC STATE SENATE DISTRICT 18 (REP),WAKE,01-47,WAKE_01-47,148,Chris Stock,88,Cheryl Caulfield,60,59.459459,40.540541,18.918919,"[{'candidate': 'Chris Stock', 'votes': 88, 'sh...",01-47
17,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-01,WAKE_02-01,189,Chris Stock,99,Cheryl Caulfield,90,52.380952,47.619048,4.761905,"[{'candidate': 'Chris Stock', 'votes': 99, 'sh...",02-01
18,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-02,WAKE_02-02,384,Chris Stock,224,Cheryl Caulfield,160,58.333333,41.666667,16.666667,"[{'candidate': 'Chris Stock', 'votes': 224, 's...",02-02
19,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-03,WAKE_02-03,192,Chris Stock,104,Cheryl Caulfield,88,54.166667,45.833333,8.333333,"[{'candidate': 'Chris Stock', 'votes': 104, 's...",02-03
20,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-04,WAKE_02-04,164,Chris Stock,93,Cheryl Caulfield,71,56.707317,43.292683,13.414634,"[{'candidate': 'Chris Stock', 'votes': 93, 'sh...",02-04
21,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-05,WAKE_02-05,63,Chris Stock,39,Cheryl Caulfield,24,61.904762,38.095238,23.809524,"[{'candidate': 'Chris Stock', 'votes': 39, 'sh...",02-05
22,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-06,WAKE_02-06,195,Chris Stock,123,Cheryl Caulfield,72,63.076923,36.923077,26.153846,"[{'candidate': 'Chris Stock', 'votes': 123, 's...",02-06
23,NC STATE SENATE DISTRICT 18 (REP),WAKE,08-04,WAKE_08-04,123,Cheryl Caulfield,66,Chris Stock,57,53.658537,46.341463,7.317073,"[{'candidate': 'Cheryl Caulfield', 'votes': 66...",08-04
24,NC STATE SENATE DISTRICT 18 (REP),WAKE,08-07,WAKE_08-07,164,Chris Stock,92,Cheryl Caulfield,72,56.097561,43.902439,12.195122,"[{'candidate': 'Chris Stock', 'votes': 92, 'sh...",08-07
25,NC STATE SENATE DISTRICT 18 (REP),WAKE,09-01,WAKE_09-01,108,Chris Stock,72,Cheryl Caulfield,36,66.666667,33.333333,33.333333,"[{'candidate': 'Chris Stock', 'votes': 72, 'sh...",09-01
26,NC STATE SENATE DISTRICT 18 (REP),WAKE,09-03,WAKE_09-03,164,Chris Stock,97,Cheryl Caulfield,67,59.146341,40.853659,18.292683,"[{'candidate': 'Chris Stock', 'votes': 97, 'sh...",09-03
27,NC STATE SENATE DISTRICT 18 (REP),WAKE,10-01,WAKE_10-01,92,Chris Stock,59,Cheryl Caulfield,33,64.130435,35.869565,28.260870,"[{'candidate': 'Chris Stock', 'votes': 59, 'sh...",10-01
28,NC STATE SENATE DISTRICT 18 (REP),WAKE,10-02,WAKE_10-02,91,Cheryl Caulfield,46,Chris Stock,45,50.549451,49.450549,1.098901,"[{'candidate': 'Cheryl Caulfield', 'votes': 46...",10-02
29,NC STATE SENATE DISTRICT 18 (REP),WAKE,14-01,WAKE_14-01,88,Chris Stock,62,Cheryl Caulfield,26,70.454545,29.545455,40.909091,"[{'candidate': 'Chris Stock', 'votes': 62, 'sh...",14-01
30,NC STATE SENATE DISTRICT 18 (REP),WAKE,14-02,WAKE_14-02,533,Chris Stock,318,Cheryl Caulfield,215,59.662289,40.337711,19.324578,"[{'candidate': 'Chris Stock', 'votes': 318, 's...",14-02
31,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-03,WAKE_19-03,146,Cheryl Caulfield,106,Chris Stock,40,72.602740,27.397260,45.205479,"[{'candidate': 'Cheryl Caulfield', 'votes': 10...",19-03
32,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-05,WAKE_19-05,246,Chris Stock,145,Cheryl Caulfield,101,58.943089,41.056911,17.886179,"[{'candidate': 'Chris Stock', 'votes': 145, 's...",19-05
33,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-07,WAKE_19-07,235,Cheryl Caulfield,137,Chris Stock,98,58.297872,41.702128,16.595745,"[{'candidate': 'Cheryl Caulfield', 'votes': 13...",19-07
34,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-09,WAKE_19-09,325,Chris Stock,182,Cheryl Caulfield,143,56.000000,44.000000,12.000000,"[{'candidate': 'Chris Stock', 'votes': 182, 's...",19-09
35,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-11,WAKE_19-11,143,Cheryl Caulfield,76,Chris Stock,67,53.146853,46.853147,6.293706,"[{'candidate': 'Cheryl Caulfield', 'votes': 76...",19-11
36,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-14,WAKE_19-14,40,Chris Stock,21,Cheryl Caulfield,19,52.500000,47.500000,5.000000,"[{'candidate': 'Chris Stock', 'votes': 21, 'sh...",19-14
37,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-15,WAKE_19-15,143,Chris Stock,103,Cheryl Caulfield,40,72.027972,27.972028,44.055944,"[{'candidate': 'Chris Stock', 'votes': 103, 's...",19-15
38,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-16,WAKE_19-16,96,Cheryl Caulfield,49,Chris Stock,47,51.041667,48.958333,2.083333,"[{'candidate': 'Cheryl Caulfield', 'votes': 49...",19-16
39,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-18,WAKE_19-18,204,Chris Stock,105,Cheryl Caulfield,99,51.470588,48.529412,2.941176,"[{'candidate': 'Chris Stock', 'votes': 105, 's...",19-18
40,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-20,WAKE_19-20,222,Cheryl Caulfield,133,Chris Stock,89,59.909910,40.090090,19.819820,"[{'candidate': 'Cheryl Caulfield', 'votes': 13...",19-20
41,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-22,WAKE_19-22,111,Chris Stock,64,Cheryl Caulfield,47,57.657658,42.342342,15.315315,"[{'candidate': 'Chris Stock', 'votes': 64, 'sh...",19-22
42,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-23,WAKE_19-23,162,Chris Stock,88,Cheryl Caulfield,74,54.320988,45.679012,8.641975,"[{'candidate': 'Chris Stock', 'votes': 88, 'sh...",19-23
43,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-24,WAKE_19-24,234,Cheryl Caulfield,126,Chris Stock,108,53.846154,46.153846,7.692308,"[{'candidate': 'Cheryl Caulfield', 'votes': 12...",19-24
44,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-25,WAKE_19-25,152,Chris Stock,89,Cheryl Caulfield,63,58.552632,41.447368,17.105263,"[{'candidate': 'Chris Stock', 'votes': 89, 'sh...",19-25

In [1101]:
# We will use both precinct id and county name to join to have more precision
# Durham's "01" could potentially match with Wake's "01-01". Joining with both
# normalized county name and precinct id will prevent this.
contest_precincts_gdf["county_join"] = (
    contest_precincts_gdf["county_nam"]
    .str.strip()
    .str.upper()
)

contest_summary_df["county_join"] = (
    contest_summary_df["County"]
    .str.strip()
    .str.upper()
)

In [1102]:
contest_precincts_gdf

,id,county_id,prec_id,enr_desc,county_nam,Shape_Leng,Shape_Area,of_prec_id,geometry,precinct_join,county_join
59,105,92,01-05,01-05,WAKE,14500.105940,1.325901e+07,NaN,"POLYGON ((2104962.991 746518.459, 2104960.007 ...",01-05,WAKE
71,110,92,01-09,01-09,WAKE,12038.234692,8.161909e+06,NaN,"POLYGON ((2106835.489 746138.993, 2106712.756 ...",01-09,WAKE
114,99,92,01-01,01-01,WAKE,16835.331171,1.549578e+07,NaN,"POLYGON ((2100440.458 741338.285, 2100440.556 ...",01-01,WAKE
116,101,92,01-02,01-02,WAKE,24437.015415,2.445547e+07,NaN,"POLYGON ((2096969.047 743377.041, 2096967.151 ...",01-02,WAKE
117,102,92,01-03,01-03,WAKE,21790.186717,2.242057e+07,NaN,"POLYGON ((2096391.936 746636.928, 2096320.174 ...",01-03,WAKE
...,...,...,...,...,...,...,...,...,...,...,...
2623,3141,92,13-12,13-12,WAKE,40066.315909,4.649720e+07,NaN,"POLYGON ((2121521.829 766440.325, 2121587.911 ...",13-12,WAKE
2624,3142,92,12-12,12-12,WAKE,46001.066465,8.927364e+07,NaN,"POLYGON ((2074291.413 679114.557, 2074060.621 ...",12-12,WAKE
2625,3143,92,12-13,12-13,WAKE,50225.930446,1.275286e+08,NaN,"POLYGON ((2067423.477 669347.8, 2067409.868 66...",12-13,WAKE
2626,3144,92,05-09,05-09,WAKE,26574.404656,4.180295e+07,NaN,"POLYGON ((2047460.895 752794.873, 2047335.208 ...",05-09,WAKE
2627,3145,92,05-10,05-10,WAKE,54128.846329,1.145843e+08,NaN,"POLYGON ((2037950.618 753669.957, 2037929.585 ...",05-10,WAKE

In [1103]:
contest_summary_df

,Contest Name,County,Precinct,county_precinct,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results,precinct_join,county_join
0,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,ANTI,GRANVILLE_ANTI,101,Chris Stock,63,Cheryl Caulfield,38,62.376238,37.623762,24.752475,"[{'candidate': 'Chris Stock', 'votes': 63, 'sh...",ANTI,GRANVILLE
1,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,BERE,GRANVILLE_BERE,240,Chris Stock,167,Cheryl Caulfield,73,69.583333,30.416667,39.166667,"[{'candidate': 'Chris Stock', 'votes': 167, 's...",BERE,GRANVILLE
2,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,BTNR,GRANVILLE_BTNR,218,Chris Stock,161,Cheryl Caulfield,57,73.853211,26.146789,47.706422,"[{'candidate': 'Chris Stock', 'votes': 161, 's...",BTNR,GRANVILLE
3,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CORI,GRANVILLE_CORI,306,Chris Stock,202,Cheryl Caulfield,104,66.013072,33.986928,32.026144,"[{'candidate': 'Chris Stock', 'votes': 202, 's...",CORI,GRANVILLE
4,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CRDL,GRANVILLE_CRDL,107,Chris Stock,75,Cheryl Caulfield,32,70.093458,29.906542,40.186916,"[{'candidate': 'Chris Stock', 'votes': 75, 'sh...",CRDL,GRANVILLE
5,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,CRDM,GRANVILLE_CRDM,472,Chris Stock,332,Cheryl Caulfield,140,70.338983,29.661017,40.677966,"[{'candidate': 'Chris Stock', 'votes': 332, 's...",CRDM,GRANVILLE
6,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,EAOX,GRANVILLE_EAOX,135,Chris Stock,104,Cheryl Caulfield,31,77.037037,22.962963,54.074074,"[{'candidate': 'Chris Stock', 'votes': 104, 's...",EAOX,GRANVILLE
7,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,MTEN,GRANVILLE_MTEN,579,Chris Stock,391,Cheryl Caulfield,188,67.530225,32.469775,35.060449,"[{'candidate': 'Chris Stock', 'votes': 391, 's...",MTEN,GRANVILLE
8,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,OKHL,GRANVILLE_OKHL,163,Chris Stock,111,Cheryl Caulfield,52,68.098160,31.901840,36.196319,"[{'candidate': 'Chris Stock', 'votes': 111, 's...",OKHL,GRANVILLE
9,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SALM,GRANVILLE_SALM,234,Chris Stock,166,Cheryl Caulfield,68,70.940171,29.059829,41.880342,"[{'candidate': 'Chris Stock', 'votes': 166, 's...",SALM,GRANVILLE
10,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SASS,GRANVILLE_SASS,277,Chris Stock,201,Cheryl Caulfield,76,72.563177,27.436823,45.126354,"[{'candidate': 'Chris Stock', 'votes': 201, 's...",SASS,GRANVILLE
11,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,SOOX,GRANVILLE_SOOX,77,Chris Stock,64,Cheryl Caulfield,13,83.116883,16.883117,66.233766,"[{'candidate': 'Chris Stock', 'votes': 64, 'sh...",SOOX,GRANVILLE
12,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,TYHO,GRANVILLE_TYHO,631,Chris Stock,476,Cheryl Caulfield,155,75.435816,24.564184,50.871632,"[{'candidate': 'Chris Stock', 'votes': 476, 's...",TYHO,GRANVILLE
13,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,WILT,GRANVILLE_WILT,846,Chris Stock,551,Cheryl Caulfield,295,65.130024,34.869976,30.260047,"[{'candidate': 'Chris Stock', 'votes': 551, 's...",WILT,GRANVILLE
14,NC STATE SENATE DISTRICT 18 (REP),GRANVILLE,WOEL,GRANVILLE_WOEL,116,Chris Stock,86,Cheryl Caulfield,30,74.137931,25.862069,48.275862,"[{'candidate': 'Chris Stock', 'votes': 86, 'sh...",WOEL,GRANVILLE
15,NC STATE SENATE DISTRICT 18 (REP),WAKE,01-42,WAKE_01-42,154,Chris Stock,80,Cheryl Caulfield,74,51.948052,48.051948,3.896104,"[{'candidate': 'Chris Stock', 'votes': 80, 'sh...",01-42,WAKE
16,NC STATE SENATE DISTRICT 18 (REP),WAKE,01-47,WAKE_01-47,148,Chris Stock,88,Cheryl Caulfield,60,59.459459,40.540541,18.918919,"[{'candidate': 'Chris Stock', 'votes': 88, 'sh...",01-47,WAKE
17,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-01,WAKE_02-01,189,Chris Stock,99,Cheryl Caulfield,90,52.380952,47.619048,4.761905,"[{'candidate': 'Chris Stock', 'votes': 99, 'sh...",02-01,WAKE
18,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-02,WAKE_02-02,384,Chris Stock,224,Cheryl Caulfield,160,58.333333,41.666667,16.666667,"[{'candidate': 'Chris Stock', 'votes': 224, 's...",02-02,WAKE
19,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-03,WAKE_02-03,192,Chris Stock,104,Cheryl Caulfield,88,54.166667,45.833333,8.333333,"[{'candidate': 'Chris Stock', 'votes': 104, 's...",02-03,WAKE
20,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-04,WAKE_02-04,164,Chris Stock,93,Cheryl Caulfield,71,56.707317,43.292683,13.414634,"[{'candidate': 'Chris Stock', 'votes': 93, 'sh...",02-04,WAKE
21,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-05,WAKE_02-05,63,Chris Stock,39,Cheryl Caulfield,24,61.904762,38.095238,23.809524,"[{'candidate': 'Chris Stock', 'votes': 39, 'sh...",02-05,WAKE
22,NC STATE SENATE DISTRICT 18 (REP),WAKE,02-06,WAKE_02-06,195,Chris Stock,123,Cheryl Caulfield,72,63.076923,36.923077,26.153846,"[{'candidate': 'Chris Stock', 'votes': 123, 's...",02-06,WAKE
23,NC STATE SENATE DISTRICT 18 (REP),WAKE,08-04,WAKE_08-04,123,Cheryl Caulfield,66,Chris Stock,57,53.658537,46.341463,7.317073,"[{'candidate': 'Cheryl Caulfield', 'votes': 66...",08-04,WAKE
24,NC STATE SENATE DISTRICT 18 (REP),WAKE,08-07,WAKE_08-07,164,Chris Stock,92,Cheryl Caulfield,72,56.097561,43.902439,12.195122,"[{'candidate': 'Chris Stock', 'votes': 92, 'sh...",08-07,WAKE
25,NC STATE SENATE DISTRICT 18 (REP),WAKE,09-01,WAKE_09-01,108,Chris Stock,72,Cheryl Caulfield,36,66.666667,33.333333,33.333333,"[{'candidate': 'Chris Stock', 'votes': 72, 'sh...",09-01,WAKE
26,NC STATE SENATE DISTRICT 18 (REP),WAKE,09-03,WAKE_09-03,164,Chris Stock,97,Cheryl Caulfield,67,59.146341,40.853659,18.292683,"[{'candidate': 'Chris Stock', 'votes': 97, 'sh...",09-03,WAKE
27,NC STATE SENATE DISTRICT 18 (REP),WAKE,10-01,WAKE_10-01,92,Chris Stock,59,Cheryl Caulfield,33,64.130435,35.869565,28.260870,"[{'candidate': 'Chris Stock', 'votes': 59, 'sh...",10-01,WAKE
28,NC STATE SENATE DISTRICT 18 (REP),WAKE,10-02,WAKE_10-02,91,Cheryl Caulfield,46,Chris Stock,45,50.549451,49.450549,1.098901,"[{'candidate': 'Cheryl Caulfield', 'votes': 46...",10-02,WAKE
29,NC STATE SENATE DISTRICT 18 (REP),WAKE,14-01,WAKE_14-01,88,Chris Stock,62,Cheryl Caulfield,26,70.454545,29.545455,40.909091,"[{'candidate': 'Chris Stock', 'votes': 62, 'sh...",14-01,WAKE
30,NC STATE SENATE DISTRICT 18 (REP),WAKE,14-02,WAKE_14-02,533,Chris Stock,318,Cheryl Caulfield,215,59.662289,40.337711,19.324578,"[{'candidate': 'Chris Stock', 'votes': 318, 's...",14-02,WAKE
31,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-03,WAKE_19-03,146,Cheryl Caulfield,106,Chris Stock,40,72.602740,27.397260,45.205479,"[{'candidate': 'Cheryl Caulfield', 'votes': 10...",19-03,WAKE
32,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-05,WAKE_19-05,246,Chris Stock,145,Cheryl Caulfield,101,58.943089,41.056911,17.886179,"[{'candidate': 'Chris Stock', 'votes': 145, 's...",19-05,WAKE
33,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-07,WAKE_19-07,235,Cheryl Caulfield,137,Chris Stock,98,58.297872,41.702128,16.595745,"[{'candidate': 'Cheryl Caulfield', 'votes': 13...",19-07,WAKE
34,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-09,WAKE_19-09,325,Chris Stock,182,Cheryl Caulfield,143,56.000000,44.000000,12.000000,"[{'candidate': 'Chris Stock', 'votes': 182, 's...",19-09,WAKE
35,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-11,WAKE_19-11,143,Cheryl Caulfield,76,Chris Stock,67,53.146853,46.853147,6.293706,"[{'candidate': 'Cheryl Caulfield', 'votes': 76...",19-11,WAKE
36,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-14,WAKE_19-14,40,Chris Stock,21,Cheryl Caulfield,19,52.500000,47.500000,5.000000,"[{'candidate': 'Chris Stock', 'votes': 21, 'sh...",19-14,WAKE
37,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-15,WAKE_19-15,143,Chris Stock,103,Cheryl Caulfield,40,72.027972,27.972028,44.055944,"[{'candidate': 'Chris Stock', 'votes': 103, 's...",19-15,WAKE
38,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-16,WAKE_19-16,96,Cheryl Caulfield,49,Chris Stock,47,51.041667,48.958333,2.083333,"[{'candidate': 'Cheryl Caulfield', 'votes': 49...",19-16,WAKE
39,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-18,WAKE_19-18,204,Chris Stock,105,Cheryl Caulfield,99,51.470588,48.529412,2.941176,"[{'candidate': 'Chris Stock', 'votes': 105, 's...",19-18,WAKE
40,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-20,WAKE_19-20,222,Cheryl Caulfield,133,Chris Stock,89,59.909910,40.090090,19.819820,"[{'candidate': 'Cheryl Caulfield', 'votes': 13...",19-20,WAKE
41,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-22,WAKE_19-22,111,Chris Stock,64,Cheryl Caulfield,47,57.657658,42.342342,15.315315,"[{'candidate': 'Chris Stock', 'votes': 64, 'sh...",19-22,WAKE
42,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-23,WAKE_19-23,162,Chris Stock,88,Cheryl Caulfield,74,54.320988,45.679012,8.641975,"[{'candidate': 'Chris Stock', 'votes': 88, 'sh...",19-23,WAKE
43,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-24,WAKE_19-24,234,Cheryl Caulfield,126,Chris Stock,108,53.846154,46.153846,7.692308,"[{'candidate': 'Cheryl Caulfield', 'votes': 12...",19-24,WAKE
44,NC STATE SENATE DISTRICT 18 (REP),WAKE,19-25,WAKE_19-25,152,Chris Stock,89,Cheryl Caulfield,63,58.552632,41.447368,17.105263,"[{'candidate': 'Chris Stock', 'votes': 89, 'sh...",19-25,WAKE

In [1104]:
contest_summary_gdf = contest_precincts_gdf.merge(
    contest_summary_df,
    left_on=["county_join", "precinct_join"],
    right_on=["county_join", "precinct_join"],
    how="left",
    indicator=True
)

In [1105]:
type(contest_summary_gdf)

geopandas.geodataframe.GeoDataFrame

In [1106]:
contest_summary_gdf

,id,county_id,prec_id,enr_desc,county_nam,Shape_Leng,Shape_Area,of_prec_id,geometry,precinct_join,...,contest_votes,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results,_merge
0,105,92,01-05,01-05,WAKE,14500.105940,1.325901e+07,NaN,"POLYGON ((2104962.991 746518.459, 2104960.007 ...",01-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,110,92,01-09,01-09,WAKE,12038.234692,8.161909e+06,NaN,"POLYGON ((2106835.489 746138.993, 2106712.756 ...",01-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,99,92,01-01,01-01,WAKE,16835.331171,1.549578e+07,NaN,"POLYGON ((2100440.458 741338.285, 2100440.556 ...",01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,101,92,01-02,01-02,WAKE,24437.015415,2.445547e+07,NaN,"POLYGON ((2096969.047 743377.041, 2096967.151 ...",01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,102,92,01-03,01-03,WAKE,21790.186717,2.242057e+07,NaN,"POLYGON ((2096391.936 746636.928, 2096320.174 ...",01-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,3141,92,13-12,13-12,WAKE,40066.315909,4.649720e+07,NaN,"POLYGON ((2121521.829 766440.325, 2121587.911 ...",13-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
227,3142,92,12-12,12-12,WAKE,46001.066465,8.927364e+07,NaN,"POLYGON ((2074291.413 679114.557, 2074060.621 ...",12-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
228,3143,92,12-13,12-13,WAKE,50225.930446,1.275286e+08,NaN,"POLYGON ((2067423.477 669347.8, 2067409.868 66...",12-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
229,3144,92,05-09,05-09,WAKE,26574.404656,4.180295e+07,NaN,"POLYGON ((2047460.895 752794.873, 2047335.208 ...",05-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
230,3145,92,05-10,05-10,WAKE,54128.846329,1.145843e+08,NaN,"POLYGON ((2037950.618 753669.957, 2037929.585 ...",05-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [1107]:
contest_summary_gdf.shape

(231, 25)

In [1108]:
# both count should match number of precincts that participated in the contest (after filtering Real Precincts == Y)
# total of both + left_only should match total number of precincts in all counties that participated in the contest
contest_summary_gdf["_merge"].value_counts()

_merge
left_only     186
both           45
right_only      0
Name: count, dtype: int64

In [1109]:
list(contest_summary_gdf)

['id',
 'county_id',
 'prec_id',
 'enr_desc',
 'county_nam',
 'Shape_Leng',
 'Shape_Area',
 'of_prec_id',
 'geometry',
 'precinct_join',
 'county_join',
 'Contest Name',
 'County',
 'Precinct',
 'county_precinct',
 'contest_votes',
 'winner',
 'winner_votes',
 'runner_up',
 'runner_up_votes',
 'winner_vote_share',
 'runner_up_vote_share',
 'margin_of_victory',
 'all_candidate_results',
 '_merge']

### Create a map key for MapBox

In [1111]:
contest_summary_gdf["county_precinct"] = (
    contest_summary_gdf["county_join"]
    + "_"
    + contest_summary_gdf["precinct_join"]
)

In [1113]:
contest_summary_gdf["county_precinct"]

0      WAKE_01-05
1      WAKE_01-09
2      WAKE_01-01
3      WAKE_01-02
4      WAKE_01-03
          ...
226    WAKE_13-12
227    WAKE_12-12
228    WAKE_12-13
229    WAKE_05-09
230    WAKE_05-10
Name: county_precinct, Length: 231, dtype: str

In [1114]:
contest_summary_gdf.rename(columns={"county_precinct": "map_key"}, inplace=True)

In [1115]:
contest_summary_gdf["map_key"]

0      WAKE_01-05
1      WAKE_01-09
2      WAKE_01-01
3      WAKE_01-02
4      WAKE_01-03
          ...
226    WAKE_13-12
227    WAKE_12-12
228    WAKE_12-13
229    WAKE_05-09
230    WAKE_05-10
Name: map_key, Length: 231, dtype: str

### For filtering out non-participating precincts on the map

In [1116]:
contest_summary_gdf["participated"] = (
    contest_summary_gdf["contest_votes"]
    .fillna(0)
    .gt(0)
)

In [1117]:
# True  = precinct participated in the contest
# False = precinct did not
contest_summary_gdf["participated"]

0      False
1      False
2      False
3      False
4      False
       ...
226    False
227    False
228    False
229    False
230    False
Name: participated, Length: 231, dtype: bool

In [1118]:
contest_summary_gdf.crs

<Projected CRS: EPSG:2264>
Name: NAD83 / North Carolina (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - North Carolina - counties of Alamance; Alexander; Alleghany; Anson; Ashe; Avery; Beaufort; Bertie; Bladen; Brunswick; Buncombe; Burke; Cabarrus; Caldwell; Camden; Carteret; Caswell; Catawba; Chatham; Cherokee; Chowan; Clay; Cleveland; Columbus; Craven; Cumberland; Currituck; Dare; Davidson; Davie; Duplin; Durham; Edgecombe; Forsyth; Franklin; Gaston; Gates; Graham; Granville; Greene; Guilford; Halifax; Harnett; Haywood; Henderson; Hertford; Hoke; Hyde; Iredell; Jackson; Johnston; Jones; Lee; Lenoir; Lincoln; Macon; Madison; Martin; McDowell; Mecklenburg; Mitchell; Montgomery; Moore; Nash; New Hanover; Northampton; Onslow; Orange; Pamlico; Pasquotank; Pender; Perquimans; Person; Pitt; Polk; Randolph; Richmond; Robeson; Rockingham; Rowan; Rutherford; Sampson; Scotland; Stanly; Stokes; Surry; Swain; Transylvania; Tyrrell; Union; Vance; Wake; Warren; Washington; Watauga; Wayne; Wilkes; Wilson; Yadkin; Yancey.
- bounds: (-84.33, 33.83, -75.38, 36.59)
Coordinate Operation:
- name: SPCS83 North Carolina zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [1119]:
contest_summary_web = contest_summary_gdf.to_crs("EPSG:4326")

### Copy/ Paste contest bounds in contest.js

In [1120]:
participating = contest_summary_web[
    contest_summary_web["participated"]
].copy()

west, south, east, north = participating.total_bounds

contest_bounds = [
    [west, south],
    [east, north]
]

print(contest_bounds)

[[np.float64(-78.80762299092058), np.float64(35.783509999663366)], [np.float64(-78.25371099138387), np.float64(36.54254100036947)]]

In [1121]:
contest_summary_web

,id,county_id,prec_id,enr_desc,county_nam,Shape_Leng,Shape_Area,of_prec_id,geometry,precinct_join,...,winner,winner_votes,runner_up,runner_up_votes,winner_vote_share,runner_up_vote_share,margin_of_victory,all_candidate_results,_merge,participated
0,105,92,01-05,01-05,WAKE,14500.105940,1.325901e+07,NaN,"POLYGON ((-78.64603 35.80064, -78.64604 35.800...",01-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
1,110,92,01-09,01-09,WAKE,12038.234692,8.161909e+06,NaN,"POLYGON ((-78.63972 35.79958, -78.64013 35.799...",01-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
2,99,92,01-01,01-01,WAKE,16835.331171,1.549578e+07,NaN,"POLYGON ((-78.66134 35.78646, -78.66134 35.786...",01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
3,101,92,01-02,01-02,WAKE,24437.015415,2.445547e+07,NaN,"POLYGON ((-78.67302 35.79209, -78.67303 35.791...",01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
4,102,92,01-03,01-03,WAKE,21790.186717,2.242057e+07,NaN,"POLYGON ((-78.67493 35.80105, -78.67517 35.801...",01-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,3141,92,13-12,13-12,WAKE,40066.315909,4.649720e+07,NaN,"POLYGON ((-78.58991 35.8552, -78.58969 35.8552...",13-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
227,3142,92,12-12,12-12,WAKE,46001.066465,8.927364e+07,NaN,"POLYGON ((-78.75004 35.61572, -78.75081 35.615...",12-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
228,3143,92,12-13,12-13,WAKE,50225.930446,1.275286e+08,NaN,"POLYGON ((-78.77322 35.58893, -78.77326 35.589...",12-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
229,3144,92,05-09,05-09,WAKE,26574.404656,4.180295e+07,NaN,"POLYGON ((-78.83991 35.8183, -78.84034 35.8182...",05-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False
230,3145,92,05-10,05-10,WAKE,54128.846329,1.145843e+08,NaN,"POLYGON ((-78.87199 35.82074, -78.87206 35.820...",05-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,False

In [1122]:
processed_file_path = os.path.join(script_dir, '..', 'data', 'processed', f'{pydash.snake_case(contest_name)}_contest_summary.geojson')
map_data_file_path = os.path.join(script_dir, '..', 'map', 'data', f'{pydash.snake_case(contest_name)}_contest_summary.geojson')

In [1124]:
contest_summary_web.to_file(processed_file_path, driver="GeoJSON")
contest_summary_web.to_file(map_data_file_path, driver="GeoJSON")