In [1]:
import sys

print(sys.executable)

/Users/binguyen/.venvs/lede/bin/python

In [145]:
import os
import geopandas as gpd
import pandas as pd
import pydash

In [2]:
script_dir = os.path.dirname(os.path.abspath('crosswalk.ipynb'))

In [3]:
shp_file_path = os.path.join(script_dir, '..', 'data', 'raw', 'geography', 'SBE_PRECINCTS_20251212', 'SBE_PRECINCTS_20251212.shp')

In [6]:
precincts_gdf = gpd.read_file(shp_file_path)

In [7]:
precincts_gdf["county_key"] = (
    precincts_gdf["county_nam"]
    .astype(str)
    .str.strip()
    .str.upper()
)

precincts_gdf["precinct_raw"] = (
    precincts_gdf["prec_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [8]:
contest_summary_file_path = os.path.join(script_dir, '..', 'data', 'processed', 'us_senate_rep_contest_summary.csv')

In [10]:
contest_summary_df = pd.read_csv(contest_summary_file_path)

In [13]:
contest_summary_df["county_key"] = (
    contest_summary_df["County"]
    .astype(str)
    .str.strip()
    .str.upper()
)

contest_summary_df["precinct_raw"] = (
    contest_summary_df["Precinct"]
    .astype(str)
    .str.strip()
    .str.upper()
)

## Check that county + precinct is actually unique

In [14]:
geo_dupes = precincts_gdf[
    precincts_gdf.duplicated(
        ["county_key", "precinct_raw"],
        keep=False
    )
].sort_values(["county_key", "precinct_raw"])

In [16]:
summary_dupes = contest_summary_df[
    contest_summary_df.duplicated(
        ["county_key", "precinct_raw"],
        keep=False
    )
].sort_values(["county_key", "precinct_raw"])

In [18]:
print("Geo duplicates:", len(geo_dupes))
print("Summary duplicates:", len(summary_dupes))

Geo duplicates: 0
Summary duplicates: 0

## Do an outer merge for diagnosis

In [19]:
diagnostic = precincts_gdf[
    ["county_key", "precinct_raw"]
].merge(
    contest_summary_df[
        ["county_key", "precinct_raw"]
    ],
    on=["county_key", "precinct_raw"],
    how="outer",
    indicator=True
)

In [20]:
diagnostic["_merge"].value_counts()

_merge
both          2223
right_only     410
left_only      409
Name: count, dtype: int64

Those last two groups are what we need to investigate.

- both = exact matches
- left_only = polygon exists but no election-result match
- right_only = election-result precinct exists but no polygon match

## Pull out all mismatches

In [21]:
geo_unmatched = (
    diagnostic[
        diagnostic["_merge"] == "left_only"
    ]
    [["county_key", "precinct_raw"]]
    .sort_values(["county_key", "precinct_raw"])
)

results_unmatched = (
    diagnostic[
        diagnostic["_merge"] == "right_only"
    ]
    [["county_key", "precinct_raw"]]
    .sort_values(["county_key", "precinct_raw"])
)

In [22]:
print(geo_unmatched.to_string(index=False))

 county_key precinct_raw
   ALAMANCE           01
   ALAMANCE           02
   ALAMANCE          035
   ALAMANCE           04
   ALAMANCE           05
   ALAMANCE          063
   ALAMANCE          064
   ALAMANCE           07
  ALLEGHANY           01
  ALLEGHANY           04
       ASHE           02
       ASHE           03
       ASHE           04
       ASHE           06
       ASHE           07
       ASHE           08
       ASHE           09
      AVERY           01
      AVERY           02
      AVERY           03
      AVERY           04
      AVERY           05
      AVERY           06
      AVERY           07
      AVERY           08
      AVERY           09
   BUNCOMBE         01.1
   BUNCOMBE         02.1
   BUNCOMBE         03.1
   BUNCOMBE         04.1
   BUNCOMBE         05.1
   BUNCOMBE         06.1
   BUNCOMBE         07.1
   BUNCOMBE         08.2
   BUNCOMBE         08.3
   BUNCOMBE         09.1
      BURKE         0001
      BURKE         0003
      BURKE         0011
      BURKE         0012
      BURKE         0013
      BURKE         0014
      BURKE         0015
      BURKE         0018
      BURKE         0019
      BURKE         0020
      BURKE         0021
      BURKE         0022
      BURKE         0024
      BURKE         0031
      BURKE         0034
      BURKE         0035
      BURKE         0036
      BURKE         0038
      BURKE         0039
      BURKE         0040
      BURKE         0048
      BURKE         0051
      BURKE         0052
      BURKE         0062
      BURKE         0064
      BURKE         0066
      BURKE         0070
      BURKE         0071
      BURKE         0072
    CATAWBA           01
    CATAWBA           02
    CATAWBA           03
    CATAWBA           04
    CATAWBA           05
    CATAWBA           06
    CATAWBA           07
    CATAWBA           08
    CATAWBA           09
     CRAVEN           02
     CRAVEN           03
     CRAVEN           05
     CRAVEN           07
   DAVIDSON           04
   DAVIDSON           06
   DAVIDSON           08
      DAVIE           01
      DAVIE           02
      DAVIE           03
      DAVIE           04
      DAVIE           05
      DAVIE           06
      DAVIE           07
      DAVIE           08
      DAVIE           09
     DURHAM           01
     DURHAM           02
     DURHAM           03
     DURHAM           04
     DURHAM           05
     DURHAM           06
     DURHAM           07
     DURHAM           08
     DURHAM           09
  EDGECOMBE         0101
  EDGECOMBE         0102
  EDGECOMBE         0103
  EDGECOMBE         0104
  EDGECOMBE         0201
  EDGECOMBE         0301
  EDGECOMBE         0401
  EDGECOMBE         0501
  EDGECOMBE         0601
  EDGECOMBE         0701
  EDGECOMBE         0801
  EDGECOMBE         0901
    FORSYTH          012
    FORSYTH          013
    FORSYTH          014
    FORSYTH          015
    FORSYTH          016
    FORSYTH          017
    FORSYTH          021
    FORSYTH          031
    FORSYTH          032
    FORSYTH          033
    FORSYTH          034
    FORSYTH          042
    FORSYTH          043
    FORSYTH          051
    FORSYTH          052
    FORSYTH          053
    FORSYTH          054
    FORSYTH          055
    FORSYTH          061
    FORSYTH          062
    FORSYTH          063
    FORSYTH          064
    FORSYTH          065
    FORSYTH          066
    FORSYTH          067
    FORSYTH          068
    FORSYTH          071
    FORSYTH          073
    FORSYTH          074
    FORSYTH          075
    FORSYTH          076
    FORSYTH          077
    FORSYTH          081
    FORSYTH          083
    FORSYTH          084
    FORSYTH          085
    FORSYTH          091
    FORSYTH          092
   FRANKLIN           01
   FRANKLIN           02
   FRANKLIN           03
   FRANKLIN           05
   FRANKLIN           06
   FRANKLIN           07
   FRANKLIN           08
   FRANKLIN           09
       HOKE           01
       HOKE           02
       HOKE           03
       HOKE           04
       HOKE           05
      MACON           01
      MACON           02
      MACON           03
      MACON           04
      MACON           05
      MACON           06
      MACON           07
      MACON           08
      MACON           09
MECKLENBURG          001
MECKLENBURG          002
MECKLENBURG          003
MECKLENBURG          004
MECKLENBURG          005
MECKLENBURG          006
MECKLENBURG          007
MECKLENBURG          008
MECKLENBURG          009
MECKLENBURG          010
MECKLENBURG          011
MECKLENBURG          012
MECKLENBURG          013
MECKLENBURG          014
MECKLENBURG          015
MECKLENBURG          016
MECKLENBURG          017
MECKLENBURG          018
MECKLENBURG          019
MECKLENBURG          020
MECKLENBURG          021
MECKLENBURG          022
MECKLENBURG          023
MECKLENBURG          024
MECKLENBURG          025
MECKLENBURG          026
MECKLENBURG          027
MECKLENBURG          028
MECKLENBURG          029
MECKLENBURG          030
MECKLENBURG          031
MECKLENBURG          032
MECKLENBURG          033
MECKLENBURG          034
MECKLENBURG          035
MECKLENBURG          036
MECKLENBURG          037
MECKLENBURG          038
MECKLENBURG          039
MECKLENBURG          040
MECKLENBURG          041
MECKLENBURG          042
MECKLENBURG          043
MECKLENBURG          044
MECKLENBURG          045
MECKLENBURG          046
MECKLENBURG          047
MECKLENBURG          048
MECKLENBURG          049
MECKLENBURG          050
MECKLENBURG          051
MECKLENBURG          052
MECKLENBURG          053
MECKLENBURG          054
MECKLENBURG          055
MECKLENBURG          056
MECKLENBURG          057
MECKLENBURG          058
MECKLENBURG          059
MECKLENBURG          060
MECKLENBURG          061
MECKLENBURG          062
MECKLENBURG          063
MECKLENBURG          064
MECKLENBURG          065
MECKLENBURG          066
MECKLENBURG          067
MECKLENBURG          068
MECKLENBURG          069
MECKLENBURG          070
MECKLENBURG          071
MECKLENBURG          072
MECKLENBURG          073
MECKLENBURG          074
MECKLENBURG          075
MECKLENBURG          076
MECKLENBURG          077
MECKLENBURG        078.1
MECKLENBURG          079
MECKLENBURG          080
MECKLENBURG          081
MECKLENBURG          082
MECKLENBURG          083
MECKLENBURG          084
MECKLENBURG          085
MECKLENBURG          086
MECKLENBURG          087
MECKLENBURG          088
MECKLENBURG          089
MECKLENBURG          090
MECKLENBURG          091
MECKLENBURG          092
MECKLENBURG          093
MECKLENBURG          094
MECKLENBURG          095
MECKLENBURG          096
MECKLENBURG          097
MECKLENBURG          098
MECKLENBURG          099
   MITCHELL           02
   MITCHELL           03
   MITCHELL           04
   MITCHELL           05
   MITCHELL           06
   MITCHELL           07
   MITCHELL           09
       PITT         0101
       PITT         0301
       PITT         0401
       PITT         0501
       PITT         0601
       PITT         0701
       PITT         0901
   RICHMOND           01
   RICHMOND           02
   RICHMOND           08
   RICHMOND           09
    ROBESON           01
    ROBESON           02
    ROBESON           03
    ROBESON           04
    ROBESON           07
    ROBESON           08
    ROBESON           09
      ROWAN           01
      ROWAN           02
      ROWAN           03
      ROWAN           04
      ROWAN           07
      ROWAN           08
      ROWAN           09
   SCOTLAND           03
   SCOTLAND           04
   SCOTLAND           07
     STANLY         0003
     STANLY         0011
     STANLY         0014
     STANLY         0015
     STANLY         0016
     STANLY         0017
     STANLY         0018
     STANLY         0019
     STANLY         0021
     STANLY         0022
     STANLY         0023
     STANLY         0024
     STANLY         0025
     STANLY         0107
     STANLY         0108
     STANLY         0110
     STANLY         0113
     STANLY         0120
     STANLY         0126
     STANLY         0127
     STANLY         0212
     STOKES           01
     STOKES           02
     STOKES           03
     STOKES           04
     STOKES         0506
     STOKES           07
     STOKES           08
     STOKES           09
      SURRY           01
      SURRY           04
      SURRY           05
      SURRY           09
      UNION         0005
      UNION          001
      UNION         0019
      UNION          002
      UNION          003
      UNION         0030
      UNION          004
      UNION         0044
      UNION         0045
      UNION          006
      UNION          007
      UNION          008
      UNION          009
      UNION          010
      UNION          011
      UNION          012
      UNION          013
      UNION          014
      UNION          015
      UNION          016
      UNION          018
      UNION          021
      UNION          022
      UNION          023
      UNION          024
      UNION          025
      UNION          026
      UNION          027
      UNION          031
      UNION          032
      UNION          033
      UNION          034
      UNION          035
      UNION          036
      UNION          039
      UNION          040
      UNION          041
      UNION          042
      UNION          043
     WARREN          001
     WARREN          002
     WARREN          003
     WARREN          004
     WARREN          005
     WARREN          006
     WARREN          007
     WARREN          008
     WARREN          009
     WARREN          010
     WARREN          011
     WARREN          012
     WARREN          013
     WARREN          014
    WATAUGA           01
    WATAUGA           02
    WATAUGA           03
    WATAUGA           04
    WATAUGA           05
    WATAUGA           06
    WATAUGA           07
    WATAUGA           08
    WATAUGA           09
      WAYNE           01
      WAYNE           02
      WAYNE           03
      WAYNE           04
      WAYNE           05
      WAYNE           06
      WAYNE           07
      WAYNE           08
      WAYNE           09

In [23]:
print(results_unmatched.to_string(index=False))

 county_key precinct_raw
   ALAMANCE            1
   ALAMANCE            2
   ALAMANCE           35
   ALAMANCE            4
   ALAMANCE            5
   ALAMANCE           63
   ALAMANCE           64
   ALAMANCE            7
  ALLEGHANY            1
  ALLEGHANY            4
       ASHE            2
       ASHE            3
       ASHE            4
       ASHE            6
       ASHE            7
       ASHE            8
       ASHE            9
      AVERY            1
      AVERY            2
      AVERY            3
      AVERY            4
      AVERY            5
      AVERY            6
      AVERY            7
      AVERY            8
      AVERY            9
   BUNCOMBE          1.1
   BUNCOMBE          2.1
   BUNCOMBE          3.1
   BUNCOMBE          4.1
   BUNCOMBE          5.1
   BUNCOMBE          6.1
   BUNCOMBE          7.1
   BUNCOMBE          8.2
   BUNCOMBE          8.3
   BUNCOMBE          9.1
      BURKE            1
      BURKE           11
      BURKE           12
      BURKE           13
      BURKE           14
      BURKE           15
      BURKE           18
      BURKE           19
      BURKE           20
      BURKE           21
      BURKE           22
      BURKE           24
      BURKE            3
      BURKE           31
      BURKE           34
      BURKE           35
      BURKE           36
      BURKE           38
      BURKE           39
      BURKE           40
      BURKE           48
      BURKE           51
      BURKE           52
      BURKE           62
      BURKE           64
      BURKE           66
      BURKE           70
      BURKE           71
      BURKE           72
    CATAWBA            1
    CATAWBA            2
    CATAWBA            3
    CATAWBA            4
    CATAWBA            5
    CATAWBA            6
    CATAWBA            7
    CATAWBA            8
    CATAWBA            9
     CRAVEN            2
     CRAVEN            3
     CRAVEN            5
     CRAVEN            7
   DAVIDSON            4
   DAVIDSON            6
   DAVIDSON            8
      DAVIE            1
      DAVIE            2
      DAVIE            3
      DAVIE            4
      DAVIE            5
      DAVIE            6
      DAVIE            7
      DAVIE            8
      DAVIE            9
     DURHAM            1
     DURHAM            2
     DURHAM            3
     DURHAM            4
     DURHAM            5
     DURHAM            6
     DURHAM            7
     DURHAM            8
     DURHAM            9
  EDGECOMBE          101
  EDGECOMBE          102
  EDGECOMBE          103
  EDGECOMBE          104
  EDGECOMBE          201
  EDGECOMBE          301
  EDGECOMBE          401
  EDGECOMBE          501
  EDGECOMBE          601
  EDGECOMBE          701
  EDGECOMBE          801
  EDGECOMBE          901
    FORSYTH           12
    FORSYTH           13
    FORSYTH           14
    FORSYTH           15
    FORSYTH           16
    FORSYTH           17
    FORSYTH           21
    FORSYTH           31
    FORSYTH           32
    FORSYTH           33
    FORSYTH           34
    FORSYTH           42
    FORSYTH           43
    FORSYTH           51
    FORSYTH           52
    FORSYTH           53
    FORSYTH           54
    FORSYTH           55
    FORSYTH           61
    FORSYTH           62
    FORSYTH           63
    FORSYTH           64
    FORSYTH           65
    FORSYTH           66
    FORSYTH           67
    FORSYTH           68
    FORSYTH           71
    FORSYTH           73
    FORSYTH           74
    FORSYTH           75
    FORSYTH           76
    FORSYTH           77
    FORSYTH           81
    FORSYTH           83
    FORSYTH           84
    FORSYTH           85
    FORSYTH           91
    FORSYTH           92
   FRANKLIN            1
   FRANKLIN            2
   FRANKLIN            3
   FRANKLIN            5
   FRANKLIN            6
   FRANKLIN            7
   FRANKLIN            8
   FRANKLIN            9
  HENDERSON           CV
       HOKE            1
       HOKE            2
       HOKE            3
       HOKE            4
       HOKE            5
      MACON            1
      MACON            2
      MACON            3
      MACON            4
      MACON            5
      MACON            6
      MACON            7
      MACON            8
      MACON            9
MECKLENBURG            1
MECKLENBURG           10
MECKLENBURG           11
MECKLENBURG           12
MECKLENBURG           13
MECKLENBURG           14
MECKLENBURG           15
MECKLENBURG           16
MECKLENBURG           17
MECKLENBURG           18
MECKLENBURG           19
MECKLENBURG            2
MECKLENBURG           20
MECKLENBURG           21
MECKLENBURG           22
MECKLENBURG           23
MECKLENBURG           24
MECKLENBURG           25
MECKLENBURG           26
MECKLENBURG           27
MECKLENBURG           28
MECKLENBURG           29
MECKLENBURG            3
MECKLENBURG           30
MECKLENBURG           31
MECKLENBURG           32
MECKLENBURG           33
MECKLENBURG           34
MECKLENBURG           35
MECKLENBURG           36
MECKLENBURG           37
MECKLENBURG           38
MECKLENBURG           39
MECKLENBURG            4
MECKLENBURG           40
MECKLENBURG           41
MECKLENBURG           42
MECKLENBURG           43
MECKLENBURG           44
MECKLENBURG           45
MECKLENBURG           46
MECKLENBURG           47
MECKLENBURG           48
MECKLENBURG           49
MECKLENBURG            5
MECKLENBURG           50
MECKLENBURG           51
MECKLENBURG           52
MECKLENBURG           53
MECKLENBURG           54
MECKLENBURG           55
MECKLENBURG           56
MECKLENBURG           57
MECKLENBURG           58
MECKLENBURG           59
MECKLENBURG            6
MECKLENBURG           60
MECKLENBURG           61
MECKLENBURG           62
MECKLENBURG           63
MECKLENBURG           64
MECKLENBURG           65
MECKLENBURG           66
MECKLENBURG           67
MECKLENBURG           68
MECKLENBURG           69
MECKLENBURG            7
MECKLENBURG           70
MECKLENBURG           71
MECKLENBURG           72
MECKLENBURG           73
MECKLENBURG           74
MECKLENBURG           75
MECKLENBURG           76
MECKLENBURG           77
MECKLENBURG         78.1
MECKLENBURG           79
MECKLENBURG            8
MECKLENBURG           80
MECKLENBURG           81
MECKLENBURG           82
MECKLENBURG           83
MECKLENBURG           84
MECKLENBURG           85
MECKLENBURG           86
MECKLENBURG           87
MECKLENBURG           88
MECKLENBURG           89
MECKLENBURG            9
MECKLENBURG           90
MECKLENBURG           91
MECKLENBURG           92
MECKLENBURG           93
MECKLENBURG           94
MECKLENBURG           95
MECKLENBURG           96
MECKLENBURG           97
MECKLENBURG           98
MECKLENBURG           99
   MITCHELL            2
   MITCHELL            3
   MITCHELL            4
   MITCHELL            5
   MITCHELL            6
   MITCHELL            7
   MITCHELL            9
       PITT          101
       PITT          301
       PITT          401
       PITT          501
       PITT          601
       PITT          701
       PITT          901
   RICHMOND            1
   RICHMOND            2
   RICHMOND            8
   RICHMOND            9
    ROBESON            1
    ROBESON            2
    ROBESON            3
    ROBESON            4
    ROBESON            7
    ROBESON            8
    ROBESON            9
      ROWAN            1
      ROWAN            2
      ROWAN            3
      ROWAN            4
      ROWAN            7
      ROWAN            8
      ROWAN            9
   SCOTLAND            3
   SCOTLAND            4
   SCOTLAND            7
     STANLY          107
     STANLY          108
     STANLY           11
     STANLY          110
     STANLY          113
     STANLY          120
     STANLY          126
     STANLY          127
     STANLY           14
     STANLY           15
     STANLY           16
     STANLY           17
     STANLY           18
     STANLY           19
     STANLY           21
     STANLY          212
     STANLY           22
     STANLY           23
     STANLY           24
     STANLY           25
     STANLY            3
     STOKES            1
     STOKES            2
     STOKES            3
     STOKES            4
     STOKES          506
     STOKES            7
     STOKES            8
     STOKES            9
      SURRY            1
      SURRY            4
      SURRY            5
      SURRY            9
      UNION            1
      UNION           10
      UNION           11
      UNION           12
      UNION           13
      UNION           14
      UNION           15
      UNION           16
      UNION           18
      UNION           19
      UNION            2
      UNION           21
      UNION           22
      UNION           23
      UNION           24
      UNION           25
      UNION           26
      UNION           27
      UNION            3
      UNION           30
      UNION           31
      UNION           32
      UNION           33
      UNION           34
      UNION           35
      UNION           36
      UNION           39
      UNION            4
      UNION           40
      UNION           41
      UNION           42
      UNION           43
      UNION           44
      UNION           45
      UNION            5
      UNION            6
      UNION            7
      UNION            8
      UNION            9
     WARREN            1
     WARREN           10
     WARREN           11
     WARREN           12
     WARREN           13
     WARREN           14
     WARREN            2
     WARREN            3
     WARREN            4
     WARREN            5
     WARREN            6
     WARREN            7
     WARREN            8
     WARREN            9
    WATAUGA            1
    WATAUGA            2
    WATAUGA            3
    WATAUGA            4
    WATAUGA            5
    WATAUGA            6
    WATAUGA            7
    WATAUGA            8
    WATAUGA            9
      WAYNE            1
      WAYNE            2
      WAYNE            3
      WAYNE            4
      WAYNE            5
      WAYNE            6
      WAYNE            7
      WAYNE            8
      WAYNE            9

## Compare mismatches within the same county

In [24]:
candidates = results_unmatched.merge(
    geo_unmatched,
    on="county_key",
    how="left",
    suffixes=("_results", "_geo")
)

In [25]:
candidates.head(30)

   county_key precinct_raw_results precinct_raw_geo
0    ALAMANCE                    1               01
1    ALAMANCE                    1               02
2    ALAMANCE                    1              035
3    ALAMANCE                    1               04
4    ALAMANCE                    1               05
5    ALAMANCE                    1              063
6    ALAMANCE                    1              064
7    ALAMANCE                    1               07
8    ALAMANCE                    2               01
9    ALAMANCE                    2               02
10   ALAMANCE                    2              035
11   ALAMANCE                    2               04
12   ALAMANCE                    2               05
13   ALAMANCE                    2              063
14   ALAMANCE                    2              064
15   ALAMANCE                    2               07
16   ALAMANCE                   35               01
17   ALAMANCE                   35               02
18   ALAMANCE                   35              035
19   ALAMANCE                   35               04
20   ALAMANCE                   35               05
21   ALAMANCE                   35              063
22   ALAMANCE                   35              064
23   ALAMANCE                   35               07
24   ALAMANCE                    4               01
25   ALAMANCE                    4               02
26   ALAMANCE                    4              035
27   ALAMANCE                    4               04
28   ALAMANCE                    4               05
29   ALAMANCE                    4              063

## Create a normalization field only for diagnosis

In [26]:
def numeric_normalized(value):
    value = str(value).strip().upper()

    if value.isdigit():
        return str(int(value))

    return value

In [27]:
geo_unmatched = geo_unmatched.copy()
results_unmatched = results_unmatched.copy()

geo_unmatched["numeric_key"] = (
    geo_unmatched["precinct_raw"]
    .apply(numeric_normalized)
)

results_unmatched["numeric_key"] = (
    results_unmatched["precinct_raw"]
    .apply(numeric_normalized)
)

In [28]:
geo_unmatched

     county_key precinct_raw numeric_key
0      ALAMANCE           01           1
1      ALAMANCE           02           2
2      ALAMANCE          035          35
9      ALAMANCE           04           4
10     ALAMANCE           05           5
...         ...          ...         ...
2937      WAYNE           05           5
2938      WAYNE           06           6
2939      WAYNE           07           7
2940      WAYNE           08           8
2941      WAYNE           09           9

[409 rows x 3 columns]

In [29]:
results_unmatched

     county_key precinct_raw numeric_key
22     ALAMANCE            1           1
40     ALAMANCE            2           2
41     ALAMANCE           35          35
42     ALAMANCE            4           4
43     ALAMANCE            5           5
...         ...          ...         ...
2965      WAYNE            5           5
2966      WAYNE            6           6
2967      WAYNE            7           7
2968      WAYNE            8           8
2969      WAYNE            9           9

[410 rows x 3 columns]

## Find possible leading-zero matches

In [30]:
zero_candidates = results_unmatched.merge(
    geo_unmatched,
    on=["county_key", "numeric_key"],
    how="inner",
    suffixes=("_results", "_geo")
)

In [33]:
zero_candidates[
    [
        "county_key",
        "precinct_raw_results",
        "precinct_raw_geo"
    ]
].sort_values(
    ["county_key", "precinct_raw_results"]
).tail(50)

    county_key precinct_raw_results precinct_raw_geo
348      UNION                   32              032
349      UNION                   33              033
350      UNION                   34              034
351      UNION                   35              035
352      UNION                   36              036
353      UNION                   39              039
354      UNION                    4              004
355      UNION                   40              040
356      UNION                   41              041
357      UNION                   42              042
358      UNION                   43              043
359      UNION                   44             0044
360      UNION                   45             0045
361      UNION                    5             0005
362      UNION                    6              006
363      UNION                    7              007
364      UNION                    8              008
365      UNION                    9              009
366     WARREN                    1              001
367     WARREN                   10              010
368     WARREN                   11              011
369     WARREN                   12              012
370     WARREN                   13              013
371     WARREN                   14              014
372     WARREN                    2              002
373     WARREN                    3              003
374     WARREN                    4              004
375     WARREN                    5              005
376     WARREN                    6              006
377     WARREN                    7              007
378     WARREN                    8              008
379     WARREN                    9              009
380    WATAUGA                    1               01
381    WATAUGA                    2               02
382    WATAUGA                    3               03
383    WATAUGA                    4               04
384    WATAUGA                    5               05
385    WATAUGA                    6               06
386    WATAUGA                    7               07
387    WATAUGA                    8               08
388    WATAUGA                    9               09
389      WAYNE                    1               01
390      WAYNE                    2               02
391      WAYNE                    3               03
392      WAYNE                    4               04
393      WAYNE                    5               05
394      WAYNE                    6               06
395      WAYNE                    7               07
396      WAYNE                    8               08
397      WAYNE                    9               09

## Detect ambiguous normalization
This is the crucial safeguard given what you discovered.

Suppose within one county the shapefile contains BOTH:
- 1
- 01

and the election results contain:
- 1

Then stripping leading zeros produces:
- 1  → 1
- 01 → 1

We have no basis for deciding which polygon is correct.

Find those cases:

Anything returned here should be manually investigated.

Do not automatically join it.

In [34]:
ambiguity = (
    zero_candidates
    .groupby(
        ["county_key", "precinct_raw_results"]
    )
    .size()
    .reset_index(name="possible_geo_matches")
)

ambiguity = ambiguity[
    ambiguity["possible_geo_matches"] > 1
]

In [35]:
ambiguity

Empty DataFrame
Columns: [county_key, precinct_raw_results, possible_geo_matches]
Index: []

## Separate safe matches from ambiguous matches

In [36]:
match_counts = (
    zero_candidates
    .groupby(
        ["county_key", "precinct_raw_results"]
    )
    .size()
    .rename("match_count")
    .reset_index()
)

zero_candidates = zero_candidates.merge(
    match_counts,
    on=["county_key", "precinct_raw_results"]
)

In [37]:
safe_zero_matches = zero_candidates[
    zero_candidates["match_count"] == 1
].copy()

In [38]:
ambiguous_zero_matches = zero_candidates[
    zero_candidates["match_count"] > 1
].copy()

In [39]:
safe_zero_matches

    county_key precinct_raw_results numeric_key precinct_raw_geo  match_count
0     ALAMANCE                    1           1               01            1
1     ALAMANCE                    2           2               02            1
2     ALAMANCE                   35          35              035            1
3     ALAMANCE                    4           4               04            1
4     ALAMANCE                    5           5               05            1
..         ...                  ...         ...              ...          ...
393      WAYNE                    5           5               05            1
394      WAYNE                    6           6               06            1
395      WAYNE                    7           7               07            1
396      WAYNE                    8           8               08            1
397      WAYNE                    9           9               09            1

[398 rows x 5 columns]

In [40]:
ambiguous_zero_matches

Empty DataFrame
Columns: [county_key, precinct_raw_results, numeric_key, precinct_raw_geo, match_count]
Index: []

## Build an explicit crosswalk

In [41]:
# For exact matches

exact_crosswalk = diagnostic[
    diagnostic["_merge"] == "both"
][
    ["county_key", "precinct_raw"]
].copy()

exact_crosswalk["results_id"] = exact_crosswalk["precinct_raw"]
exact_crosswalk["geo_id"] = exact_crosswalk["precinct_raw"]
exact_crosswalk["match_method"] = "exact"

exact_crosswalk = exact_crosswalk[
    ["county_key", "results_id", "geo_id", "match_method"]
]

In [42]:
# For safe zero matches

zero_crosswalk = safe_zero_matches[
    [
        "county_key",
        "precinct_raw_results",
        "precinct_raw_geo"
    ]
].copy()

zero_crosswalk = zero_crosswalk.rename(columns={
    "precinct_raw_results": "results_id",
    "precinct_raw_geo": "geo_id"
})

zero_crosswalk["match_method"] = "leading_zero"

In [43]:
crosswalk = pd.concat(
    [
        exact_crosswalk,
        zero_crosswalk
    ],
    ignore_index=True
)

In [47]:
crosswalk["match_method"].value_counts()

match_method
exact           2223
leading_zero     398
Name: count, dtype: int64

## Compare crosswalk against precincts source data

In [48]:
print("Total precinct polygons:", len(precincts_gdf))

print(
    "Unique county + precinct:",
    precincts_gdf[
        ["county_key", "precinct_raw"]
    ].drop_duplicates().shape[0]
)

print(
    "Counties:",
    precincts_gdf["county_key"].nunique()
)

Total precinct polygons: 2632
Unique county + precinct: 2632
Counties: 100

## Determine which polygons have a Senate result

In [49]:
senate_geo_keys = crosswalk[
    ["county_key", "geo_id"]
].drop_duplicates()

In [50]:
senate_geo_keys = senate_geo_keys.rename(
    columns={"geo_id": "precinct_raw"}
)

In [51]:
geo_contest_check = precincts_gdf.merge(
    senate_geo_keys,
    on=["county_key", "precinct_raw"],
    how="left",
    indicator=True
)

In [52]:
geo_contest_check["_merge"].value_counts()

# Because this is a left join starting from geometry:
# both = polygon has a Senate Republican contest record
# left_only = polygon exists but has no Senate Republican record

_merge
both          2621
left_only       11
right_only       0
Name: count, dtype: int64

## Look at the polygons with no Senate record

In [53]:
no_senate_record = (
    geo_contest_check[
        geo_contest_check["_merge"] == "left_only"
    ]
    [
        ["county_key", "precinct_raw"]
    ]
    .sort_values(
        ["county_key", "precinct_raw"]
    )
)

In [55]:
print(
    "Polygons without Senate record:",
    len(no_senate_record)
)

Polygons without Senate record: 11

In [54]:
print(no_senate_record.to_string(index=False))

 county_key precinct_raw
   BUNCOMBE         01.1
   BUNCOMBE         02.1
   BUNCOMBE         03.1
   BUNCOMBE         04.1
   BUNCOMBE         05.1
   BUNCOMBE         06.1
   BUNCOMBE         07.1
   BUNCOMBE         08.2
   BUNCOMBE         08.3
   BUNCOMBE         09.1
MECKLENBURG        078.1

In [58]:
contest_summary_df["contest_votes"].eq(0).value_counts()

contest_votes
False    2617
True       16
Name: count, dtype: int64

In [60]:
summary_crosswalk_check = contest_summary_df.merge(
    crosswalk[
        ["county_key", "results_id"]
    ],
    left_on=[
        "county_key",
        "precinct_raw"
    ],
    right_on=[
        "county_key",
        "results_id"
    ],
    how="left",
    indicator=True
)

unmatched_results = (
    summary_crosswalk_check[
        summary_crosswalk_check["_merge"] == "left_only"
    ]
    .copy()
)

print(
    unmatched_results[
        [
            "county_key",
            "precinct_raw",
            "contest_votes"
        ]
    ]
    .sort_values(
        ["county_key", "precinct_raw"]
    )
    .to_string(index=False)
)

 county_key precinct_raw  contest_votes
   BUNCOMBE          1.1             29
   BUNCOMBE          2.1             19
   BUNCOMBE          3.1             22
   BUNCOMBE          4.1             37
   BUNCOMBE          5.1            113
   BUNCOMBE          6.1             68
   BUNCOMBE          7.1             35
   BUNCOMBE          8.2             53
   BUNCOMBE          8.3             70
   BUNCOMBE          9.1             76
  HENDERSON           CV            115
MECKLENBURG         78.1             36

In [61]:
print("Unmatched result precincts:", len(unmatched_results))

Unmatched result precincts: 12

In [63]:
print(
    unmatched_results[
        [
            "county_key",
            "precinct_raw",
            "contest_votes"
        ]
    ]
    .sort_values(
        ["contest_votes", "county_key", "precinct_raw"]
    )
    .to_string(index=False)
)

 county_key precinct_raw  contest_votes
   BUNCOMBE          2.1             19
   BUNCOMBE          3.1             22
   BUNCOMBE          1.1             29
   BUNCOMBE          7.1             35
MECKLENBURG         78.1             36
   BUNCOMBE          4.1             37
   BUNCOMBE          8.2             53
   BUNCOMBE          6.1             68
   BUNCOMBE          8.3             70
   BUNCOMBE          9.1             76
   BUNCOMBE          5.1            113
  HENDERSON           CV            115

In [64]:
print(
    unmatched_results["county_key"]
    .value_counts()
    .sort_index()
)

county_key
BUNCOMBE       10
HENDERSON       1
MECKLENBURG     1
Name: count, dtype: int64

In [65]:
print(
    no_senate_record["county_key"]
    .value_counts()
    .sort_index()
)

county_key
BUNCOMBE       10
MECKLENBURG     1
Name: count, dtype: int64

In [66]:
for county in ["BUNCOMBE", "MECKLENBURG"]:

    print(f"\n--- {county} ---")

    print("\nRESULTS:")
    print(
        unmatched_results.loc[
            unmatched_results["county_key"] == county,
            ["precinct_raw", "contest_votes"]
        ]
        .sort_values("precinct_raw")
        .to_string(index=False)
    )

    print("\nGEOGRAPHY:")
    print(
        no_senate_record.loc[
            no_senate_record["county_key"] == county,
            ["precinct_raw"]
        ]
        .sort_values("precinct_raw")
        .to_string(index=False)
    )

--- BUNCOMBE ---

RESULTS:
precinct_raw  contest_votes
         1.1             29
         2.1             19
         3.1             22
         4.1             37
         5.1            113
         6.1             68
         7.1             35
         8.2             53
         8.3             70
         9.1             76

GEOGRAPHY:
precinct_raw
        01.1
        02.1
        03.1
        04.1
        05.1
        06.1
        07.1
        08.2
        08.3
        09.1

--- MECKLENBURG ---

RESULTS:
precinct_raw  contest_votes
        78.1             36

GEOGRAPHY:
precinct_raw
       078.1

In [67]:
henderson_unmatched = unmatched_results[
    unmatched_results["county_key"] == "HENDERSON"
]

print(
    henderson_unmatched[
        [
            "precinct_raw",
            "contest_votes"
        ]
    ].to_string(index=False)
)

precinct_raw  contest_votes
          CV            115

In [70]:
print("RESULT PRECINCTS")

print(
    contest_summary_df.loc[
        contest_summary_df["county_key"] == "HENDERSON",
        ["precinct_raw", "contest_votes"]
    ]
    .sort_values("precinct_raw")
    .to_string(index=False)
)

RESULT PRECINCTS
precinct_raw  contest_votes
          AR            209
          AT            530
          BC            142
          BK            104
          CB            236
          CC            466
          CV            115
          ED            473
          EF            324
          ES            297
          EV            401
          FL            376
          FR            622
          GM            143
          GR            477
          HC            360
          HS            399
        HV-1            271
        HV-2            169
        HV-3            245
          LJ            296
          LP            271
          MG            136
          NB            528
          NE            216
          NM            366
          NW            216
          PR            316
          PV            284
          RG            313
          RR            161
          SB            518
          SE            154
          SM            538
          SW            345

In [71]:
print("GEOGRAPHY PRECINCTS")

print(
    precincts_gdf.loc[
        precincts_gdf["county_key"] == "HENDERSON",
        ["precinct_raw"]
    ]
    .sort_values("precinct_raw")
    .to_string(index=False)
)

GEOGRAPHY PRECINCTS
precinct_raw
          AR
          AT
          BC
          BK
          CB
          CC
          ED
          EF
          ES
          EV
          FL
          FR
          GM
          GR
          HC
          HS
        HV-1
        HV-2
        HV-3
          LJ
          LP
          MG
          NB
          NE
          NM
          NW
          PR
          PV
          RG
          RR
          SB
          SE
          SM
          SW

## Normalize leading zero mismatches with decimal
Normalize only the numeric part before the decimal

In [73]:
def normalize_decimal_precinct(value):
    value = str(value).strip().upper()

    parts = value.split(".")

    if len(parts) == 2:
        left, right = parts

        if left.isdigit() and right.isdigit():
            return f"{int(left)}.{right}"

    return value

In [74]:
normalize_decimal_precinct("01.1")
# "1.1"

normalize_decimal_precinct("078.1")
# "78.1"

normalize_decimal_precinct("08.2")
# "8.2"

'8.2'

In [75]:
results_remaining = unmatched_results.copy()
geo_remaining = no_senate_record.copy()

results_remaining["decimal_key"] = (
    results_remaining["precinct_raw"]
    .apply(normalize_decimal_precinct)
)

geo_remaining["decimal_key"] = (
    geo_remaining["precinct_raw"]
    .apply(normalize_decimal_precinct)
)

In [76]:
decimal_candidates = results_remaining.merge(
    geo_remaining,
    on=["county_key", "decimal_key"],
    how="inner",
    suffixes=("_results", "_geo")
)

In [77]:
decimal_candidates[
    [
        "county_key",
        "precinct_raw_results",
        "precinct_raw_geo"
    ]
].sort_values(
    ["county_key", "precinct_raw_results"]
)

     county_key precinct_raw_results precinct_raw_geo
0      BUNCOMBE                  1.1             01.1
1      BUNCOMBE                  2.1             02.1
2      BUNCOMBE                  3.1             03.1
3      BUNCOMBE                  4.1             04.1
4      BUNCOMBE                  5.1             05.1
5      BUNCOMBE                  6.1             06.1
6      BUNCOMBE                  7.1             07.1
7      BUNCOMBE                  8.2             08.2
8      BUNCOMBE                  8.3             08.3
9      BUNCOMBE                  9.1             09.1
10  MECKLENBURG                 78.1            078.1

## Check ambiguity exactly as before
Even though these look unambiguous, keep the safeguard:

In [78]:
decimal_match_counts = (
    decimal_candidates
    .groupby(
        ["county_key", "precinct_raw_results"]
    )
    .size()
    .reset_index(name="match_count")
)

decimal_match_counts[
    decimal_match_counts["match_count"] > 1
]

Empty DataFrame
Columns: [county_key, precinct_raw_results, match_count]
Index: []

## Add to the crosswalk

In [79]:
decimal_crosswalk = decimal_candidates[
    [
        "county_key",
        "precinct_raw_results",
        "precinct_raw_geo"
    ]
].copy()

decimal_crosswalk = decimal_crosswalk.rename(
    columns={
        "precinct_raw_results": "results_id",
        "precinct_raw_geo": "geo_id"
    }
)

decimal_crosswalk["match_method"] = "decimal_leading_zero"

In [80]:
crosswalk = pd.concat(
    [
        crosswalk,
        decimal_crosswalk
    ],
    ignore_index=True
)

In [81]:
crosswalk["match_method"].value_counts()

match_method
exact                   2223
leading_zero             398
decimal_leading_zero      11
Name: count, dtype: int64

Henderson County precinct CV does not exist on the NC Precinct Geo Spatial Files.

However, Henderson County precinct CV does exist on the NC Election Results for March 3, 2026 Primary and contains votes for many contests.

Contact NCBOE to understand why this precint does not have geography associated to it.

## Add specific one-offs to crosswalk

In [82]:
cv_record = pd.DataFrame({
    "county_key": ["HENDERSON"],
    "results_id": ["CV"],
    "geo_id": [pd.NA],
    "match_method": ["no_geometry"]
})

In [83]:
crosswalk = pd.concat(
    [
        crosswalk,
        cv_record
    ],
    ignore_index=True
)

In [84]:
crosswalk["match_method"].value_counts()

match_method
exact                   2223
leading_zero             398
decimal_leading_zero      11
no_geometry                1
Name: count, dtype: int64

## Crosswalk results for March 3, 2026 NC Primary US Senate Rep race

2,633 result-side precinct/reporting units

2,223  exact geographic matches
  398  integer leading-zero matches
   11  decimal leading-zero matches
    1  valid result unit with no polygon: HENDERSON / CV
──────
2,633

In [86]:
crosswalk

       county_key results_id geo_id          match_method
0        ALAMANCE        03C    03C                 exact
1        ALAMANCE        03N    03N                 exact
2        ALAMANCE       03N2   03N2                 exact
3        ALAMANCE       03SE   03SE                 exact
4        ALAMANCE       03SM   03SM                 exact
...           ...        ...    ...                   ...
2628     BUNCOMBE        8.2   08.2  decimal_leading_zero
2629     BUNCOMBE        8.3   08.3  decimal_leading_zero
2630     BUNCOMBE        9.1   09.1  decimal_leading_zero
2631  MECKLENBURG       78.1  078.1  decimal_leading_zero
2632    HENDERSON         CV   <NA>           no_geometry

[2633 rows x 4 columns]

## Save to CSV

In [85]:
output_file_path = os.path.join(script_dir, '..', 'data', 'crosswalks', 'precinct_crosswalk_2026.csv')

In [87]:
crosswalk.to_csv(output_file_path, index=False)

## Time to merge

In [89]:
senate_xwalk = contest_summary_df.merge(
    crosswalk,
    left_on=["county_key", "precinct_raw"],
    right_on=["county_key", "results_id"],
    how="left",
    validate="one_to_one"
)

In [90]:
senate_xwalk["match_method"].value_counts(dropna=False)

match_method
exact                   2223
leading_zero             398
decimal_leading_zero      11
no_geometry                1
Name: count, dtype: int64

In [91]:
# Now split the mappable results from the unmappable Henderson record

In [92]:
senate_mappable = senate_xwalk[
    senate_xwalk["geo_id"].notna()
].copy()

senate_unmapped = senate_xwalk[
    senate_xwalk["geo_id"].isna()
].copy()

In [94]:
len(senate_mappable)
# 2632

# len(senate_unmapped)
# 1

2632

In [95]:
senate_unmapped[
    ["county_key", "precinct_raw", "contest_votes", "match_method"]
]

     county_key precinct_raw  contest_votes match_method
1217  HENDERSON           CV            115  no_geometry

In [99]:
# Join the mappable results to the full statewide precinct geometry

In [97]:
senate_map = precincts_gdf.merge(
    senate_mappable,
    left_on=["county_key", "precinct_raw"],
    right_on=["county_key", "geo_id"],
    how="left",
    validate="one_to_one",
    indicator="contest_merge"
)

In [98]:
senate_map["contest_merge"].value_counts()

contest_merge
both          2632
left_only        0
right_only       0
Name: count, dtype: int64

In [100]:
# Handle the zero-vote precincts. The main rule is: do not let a 0-vote precinct inherit a fake winner from idxmax() or similar logic.

In [101]:
zero_mask = senate_map["contest_votes"].eq(0)

senate_map.loc[zero_mask, "winner"] = pd.NA
senate_map.loc[zero_mask, "winner_votes"] = 0
senate_map.loc[zero_mask, "winner_share"] = pd.NA
senate_map.loc[zero_mask, "runner_up"] = pd.NA
senate_map.loc[zero_mask, "runner_up_votes"] = 0
senate_map.loc[zero_mask, "margin_of_victory"] = pd.NA
# senate_map.loc[zero_mask, "opacity"] = 0

In [104]:
# Create an explicit status field
# Use for no_contest_record in the future with district/local contests

In [102]:
senate_map["contest_status"] = "votes"

senate_map.loc[
    senate_map["contest_votes"].eq(0),
    "contest_status"
] = "zero_votes"

In [108]:
senate_map["contest_status"].value_counts()

contest_status
votes         2616
zero_votes      16
Name: count, dtype: int64

One important point: your full Senate result total still comes from contest_summary, not senate_map, 
because **Henderson CV** is excluded spatially:

In [110]:
official_contest_votes = contest_summary_df["contest_votes"].sum()

mapped_contest_votes = senate_map["contest_votes"].sum()

unmapped_contest_votes = senate_unmapped["contest_votes"].sum()

In [112]:
print(official_contest_votes)
print(mapped_contest_votes)
print(unmapped_contest_votes)

527188
527073
115

In [111]:
official_contest_votes == mapped_contest_votes + unmapped_contest_votes

np.True_

## Export GeoJSON for MapBox

In [122]:
senate_map.columns.tolist()

['id',
 'county_id',
 'prec_id',
 'enr_desc',
 'county_nam',
 'Shape_Leng',
 'Shape_Area',
 'of_prec_id',
 'geometry',
 'county_key',
 'precinct_raw_x',
 'Contest Name',
 'County',
 'Precinct',
 'county_precinct',
 'contest_votes',
 'winner',
 'winner_votes',
 'runner_up',
 'runner_up_votes',
 'winner_vote_share',
 'runner_up_vote_share',
 'margin_of_victory',
 'all_candidate_results',
 'precinct_raw_y',
 'results_id',
 'geo_id',
 'match_method',
 'contest_merge',
 'winner_share',
 'contest_status']

In [121]:
senate_map[["precinct_raw_x", "precinct_raw_y", "prec_id"]].head(20)

   precinct_raw_x precinct_raw_y prec_id
0            LI-1           LI-1    LI-1
1              DR             DR      DR
2              RC             RC      RC
3            WS-1           WS-1    WS-1
4              ST             ST      ST
5            RE-1           RE-1    RE-1
6              WI             WI      WI
7            RE-2           RE-2    RE-2
8              MO             MO      MO
9              ED             ED      ED
10           HO-1           HO-1    HO-1
11             NB             NB      NB
12           HU-1           HU-1    HU-1
13             EC             EC      EC
14           01-A           01-A    01-A
15           0127            127    0127
16           0126            126    0126
17             25             25      25
18             24             24      24
19             23             23      23

In [123]:
senate_map = senate_map.rename(
    columns={
        "precinct_raw_x": "geo_precinct_id",
        "precinct_raw_y": "results_precinct_id"
    }
)

In [124]:
senate_map["precinct_id"] = senate_map["geo_precinct_id"]

In [125]:
senate_map.columns.tolist()

['id',
 'county_id',
 'prec_id',
 'enr_desc',
 'county_nam',
 'Shape_Leng',
 'Shape_Area',
 'of_prec_id',
 'geometry',
 'county_key',
 'geo_precinct_id',
 'Contest Name',
 'County',
 'Precinct',
 'county_precinct',
 'contest_votes',
 'winner',
 'winner_votes',
 'runner_up',
 'runner_up_votes',
 'winner_vote_share',
 'runner_up_vote_share',
 'margin_of_victory',
 'all_candidate_results',
 'results_precinct_id',
 'results_id',
 'geo_id',
 'match_method',
 'contest_merge',
 'winner_share',
 'contest_status',
 'precinct_id']

## Create map_key for MapBox

In [130]:
senate_map.rename(columns={"county_precinct": "map_key"}, inplace=True)

## Add tie column

In [149]:
senate_map["is_tie"] = (
    senate_map["contest_votes"].gt(0)
    & senate_map["winner_votes"].eq(senate_map["runner_up_votes"])
)

In [151]:
senate_map["is_tie"].value_counts()

is_tie
False    2604
True       28
Name: count, dtype: int64

## Add participating column for MapBox on-hover and click features

Contest record + 500 votes  → participated = True

Contest record +   0 votes  → participated = True

No contest record           → participated = False

In [131]:
senate_map["participated"] = (
    senate_map["contest_merge"] == "both"
)

In [150]:
senate_map[senate_map["contest_votes"] == 0]

,id,county_id,prec_id,enr_desc,county_nam,Shape_Leng,Shape_Area,of_prec_id,geometry,county_key,...,results_precinct_id,results_id,geo_id,match_method,contest_merge,winner_share,contest_status,precinct_id,participated,is_tie
81,727,32,12,MONUMENT OF FAITH CHURCH,DURHAM,13937.780640,8.738686e+06,NaN,"POLYGON ((2031829.354 810866.354, 2031745.03 8...",DURHAM,...,12,12,12,exact,both,<NA>,zero_votes,12,True,False
416,425,60,056,056,MECKLENBURG,34886.513440,5.778728e+07,NaN,"POLYGON ((1454794.351 551722.749, 1454521.239 ...",MECKLENBURG,...,56,56,056,leading_zero,both,<NA>,zero_votes,056,True,False
641,10058,34,301,ASHLEY ELEMENTARY SCHOOL,FORSYTH,18384.576812,1.345322e+07,NaN,"POLYGON ((1639326.592 862652.184, 1639260.548 ...",FORSYTH,...,301,301,301,exact,both,<NA>,zero_votes,301,True,False
735,764,33,1202,ROCKY MOUNT 2,EDGECOMBE,35734.820155,3.901044e+07,NaN,"POLYGON ((2361629.539 790293.958, 2361623.675 ...",EDGECOMBE,...,1202,1202,1202,exact,both,<NA>,zero_votes,1202,True,False
891,924,89,16,SOUTH FORK,TYRRELL,157630.059285,1.155475e+09,NaN,"POLYGON ((2790521.702 718121.026, 2790493.752 ...",TYRRELL,...,16,16,16,exact,both,<NA>,zero_votes,16,True,False
986,1839,41,G68,G68,GUILFORD,18334.170729,1.811065e+07,NaN,"POLYGON ((1772311.784 846042.497, 1772320.554 ...",GUILFORD,...,G68,G68,G68,exact,both,<NA>,zero_votes,G68,True,False
1201,1356,32,55-49,055-49,DURHAM,11089.961866,6.307735e+06,NaN,"POLYGON ((2029031.522 807855.93, 2029058.104 8...",DURHAM,...,55-49,55-49,55-49,exact,both,<NA>,zero_votes,55-49,True,False
1225,1295,32,41,WHITE ROCK BAPTIST CHURCH,DURHAM,24364.817226,2.437085e+07,NaN,"POLYGON ((2026525.706 801345.661, 2026410.924 ...",DURHAM,...,41,41,41,exact,both,<NA>,zero_votes,41,True,False
1279,1625,82,CLEA,"CLINTON, EAST",SAMPSON,202587.816801,9.450471e+08,NaN,"POLYGON ((2207291.075 449852.649, 2206990.28 4...",SAMPSON,...,CLEA,CLEA,CLEA,exact,both,<NA>,zero_votes,CLEA,True,False
1281,1627,82,CLNE,"CLINTON, NORTHEAST",SAMPSON,65575.256776,7.989404e+07,NaN,"POLYGON ((2205263.638 455478.61, 2205334.426 4...",SAMPSON,...,CLNE,CLNE,CLNE,exact,both,<NA>,zero_votes,CLNE,True,False
1283,1629,82,CLSW,"CLINTON, SOUTHWEST",SAMPSON,119243.456424,3.956746e+08,NaN,"POLYGON ((2200423.755 426589.736, 2200417.172 ...",SAMPSON,...,CLSW,CLSW,CLSW,exact,both,<NA>,zero_votes,CLSW,True,False
1284,1630,82,CLWE,"CLINTON, WEST",SAMPSON,156236.171641,7.213213e+08,NaN,"POLYGON ((2183089.044 425755.608, 2182965.659 ...",SAMPSON,...,CLWE,CLWE,CLWE,exact,both,<NA>,zero_votes,CLWE,True,False
1509,1624,82,CLCE,"CLINTON, CENTRAL",SAMPSON,55568.257160,3.679371e+07,NaN,"POLYGON ((2200296.661 451595.67, 2200394.383 4...",SAMPSON,...,CLCE,CLCE,CLCE,exact,both,<NA>,zero_votes,CLCE,True,False
1793,2005,82,KFRK,KITTY FORK,SAMPSON,176346.708698,8.663983e+08,NaN,"POLYGON ((2163437.53 474812, 2163464.856 47484...",SAMPSON,...,KFRK,KFRK,KFRK,exact,both,<NA>,zero_votes,KFRK,True,False
2168,2409,82,ROWA,ROWAN,SAMPSON,208312.374672,1.380893e+09,NaN,"POLYGON ((2209097.456 405845.474, 2208950.718 ...",SAMPSON,...,ROWA,ROWA,ROWA,exact,both,<NA>,zero_votes,ROWA,True,False
2431,10060,34,303,JOHN WESLEY AME ZION CHURCH,FORSYTH,24225.810693,1.176394e+07,NaN,"POLYGON ((1641017.038 865100.909, 1641149.603 ...",FORSYTH,...,303,303,303,exact,both,<NA>,zero_votes,303,True,False

In [152]:
senate_web = senate_map[
    [
        "map_key",
        "county_key",
        "precinct_id",
        "results_precinct_id",
        "enr_desc",
        "winner",
        "winner_votes",
        "winner_vote_share",
        "runner_up",
        "runner_up_votes",
        "runner_up_vote_share",
        "contest_votes",
        "all_candidate_results",
        "margin_of_victory",
        "contest_status",
        "participated",
        "is_tie",
        "geometry"
    ]
].copy()

In [153]:
senate_web.crs

<Projected CRS: EPSG:2264>
Name: NAD83 / North Carolina (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - North Carolina - counties of Alamance; Alexander; Alleghany; Anson; Ashe; Avery; Beaufort; Bertie; Bladen; Brunswick; Buncombe; Burke; Cabarrus; Caldwell; Camden; Carteret; Caswell; Catawba; Chatham; Cherokee; Chowan; Clay; Cleveland; Columbus; Craven; Cumberland; Currituck; Dare; Davidson; Davie; Duplin; Durham; Edgecombe; Forsyth; Franklin; Gaston; Gates; Graham; Granville; Greene; Guilford; Halifax; Harnett; Haywood; Henderson; Hertford; Hoke; Hyde; Iredell; Jackson; Johnston; Jones; Lee; Lenoir; Lincoln; Macon; Madison; Martin; McDowell; Mecklenburg; Mitchell; Montgomery; Moore; Nash; New Hanover; Northampton; Onslow; Orange; Pamlico; Pasquotank; Pender; Perquimans; Person; Pitt; Polk; Randolph; Richmond; Robeson; Rockingham; Rowan; Rutherford; Sampson; Scotland; Stanly; Stokes; Surry; Swain; Transylvania; Tyrrell; Union; Vance; Wake; Warren; Washington; Watauga; Wayne; Wilkes; Wilson; Yadkin; Yancey.
- bounds: (-84.33, 33.83, -75.38, 36.59)
Coordinate Operation:
- name: SPCS83 North Carolina zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [154]:
senate_web = senate_web.to_crs("EPSG:4326")

In [155]:
contest_name = senate_map['Contest Name'].unique()[0]
contest_name

'US SENATE (REP)'

In [156]:
processed_file_path = os.path.join(script_dir, '..', 'data', 'processed', f'{pydash.snake_case(contest_name)}_contest_summary.geojson')
map_data_file_path = os.path.join(script_dir, '..', 'map', 'data', f'{pydash.snake_case(contest_name)}_contest_summary.geojson')

In [157]:
senate_web.to_file(processed_file_path, driver="GeoJSON")
senate_web.to_file(map_data_file_path, driver="GeoJSON")

## Add bounds to contest.js

In [148]:
participating = senate_web[
    senate_web["participated"]
].copy()

west, south, east, north = participating.total_bounds

contest_bounds = [
    [west, south],
    [east, north]
]

print(contest_bounds)

[[np.float64(-84.3218209914704), np.float64(33.75287799999573)], [np.float64(-75.4001189911457), np.float64(36.588136999894786)]]